DROP TABLE IF EXISTS ElectionStarter;

DROP TABLE IF EXISTS PersonStarter;

DROP TABLE IF EXISTS ConstituencyStarter;

DROP TABLE IF EXISTS StateStarter;

DROP TABLE IF EXISTS PartyStarter;

DROP TABLE IF EXISTS Comment;

DROP TABLE IF EXISTS Starter;

DROP TABLE IF EXISTS Discussion;

DROP TABLE IF EXISTS Candidate;

DROP TABLE IF EXISTS Follows;

DROP TABLE IF EXISTS Users;

DROP TABLE IF EXISTS Stats;

DROP TABLE IF EXISTS Election;

DROP TABLE IF EXISTS NotablePersonConstituency;

DROP TABLE IF EXISTS Constituency;

DROP TABLE IF EXISTS State;

DROP TABLE IF EXISTS NotablePerson;

DROP TABLE IF EXISTS Party;

DROP TABLE IF EXISTS ActiveRelatives;

DROP TABLE IF EXISTS Person;