INSERT INTO state VALUES ('uttarakhand');
INSERT INTO state VALUES ('puducherry');
INSERT INTO state VALUES ('karnataka');
INSERT INTO state VALUES ('himachal pradesh');
INSERT INTO state VALUES ('mizoram');
INSERT INTO state VALUES ('tamil nadu');
INSERT INTO state VALUES ('daman & diu');
INSERT INTO state VALUES ('haryana');
INSERT INTO state VALUES ('punjab');
INSERT INTO state VALUES ('goa');
INSERT INTO state VALUES ('chhattisgarh');
INSERT INTO state VALUES ('kerala');
INSERT INTO state VALUES ('orissa');
INSERT INTO state VALUES ('west bengal');
INSERT INTO state VALUES ('chandigarh');
INSERT INTO state VALUES ('andhra pradesh');
INSERT INTO state VALUES ('jharkhand');
INSERT INTO state VALUES ('meghalaya');
INSERT INTO state VALUES ('assam');
INSERT INTO state VALUES ('nct of delhi');
INSERT INTO state VALUES ('lakshadweep');
INSERT INTO state VALUES ('manipur');
INSERT INTO state VALUES ('rajasthan');
INSERT INTO state VALUES ('arunachal pradesh');
INSERT INTO state VALUES ('sikkim');
INSERT INTO state VALUES ('jammu & kashmir');
INSERT INTO state VALUES ('andaman & nicobar islands');
INSERT INTO state VALUES ('bihar');
INSERT INTO state VALUES ('nagaland');
INSERT INTO state VALUES ('madhya pradesh');
INSERT INTO state VALUES ('uttar pradesh');
INSERT INTO state VALUES ('gujarat');
INSERT INTO state VALUES ('dadra & nagar haveli');
INSERT INTO state VALUES ('maharashtra');
INSERT INTO state VALUES ('tripura');
