INSERT INTO constituency VALUES ('andaman & nicobar islands', 'andaman & nicobar islands', NULL, NULL, NULL);
INSERT INTO constituency VALUES ('chandigarh', 'andaman & nicobar islands', NULL, NULL, NULL);
INSERT INTO constituency VALUES ('adilabad', 'andhra pradesh', NULL, NULL, NULL);
INSERT INTO constituency VALUES ('amalapuram', 'andhra pradesh', NULL, NULL, NULL);
INSERT INTO constituency VALUES ('anakapalli', 'andhra pradesh', NULL, NULL, NULL);
INSERT INTO constituency VALUES ('anantapur', 'andhra pradesh', NULL, NULL, NULL);
INSERT INTO constituency VALUES ('aruku', 'andhra pradesh', NULL, NULL, NULL);
INSERT INTO constituency VALUES ('bapatla', 'andhra pradesh', NULL, NULL, NULL);
INSERT INTO constituency VALUES ('bhadrachalam', 'andhra pradesh', NULL, NULL, NULL);
INSERT INTO constituency VALUES ('bhongir', 'andhra pradesh', NULL, NULL, NULL);
INSERT INTO constituency VALUES ('bobbili', 'andhra pradesh', NULL, NULL, NULL);
INSERT INTO constituency VALUES ('chelvella', 'andhra pradesh', NULL, NULL, NULL);
INSERT INTO constituency VALUES ('chittoor', 'andhra pradesh', NULL, NULL, NULL);
INSERT INTO constituency VALUES ('cuddapah', 'andhra pradesh', NULL, NULL, NULL);
INSERT INTO constituency VALUES ('eluru', 'andhra pradesh', NULL, NULL, NULL);
INSERT INTO constituency VALUES ('guntur', 'andhra pradesh', NULL, NULL, NULL);
INSERT INTO constituency VALUES ('hanamkonda', 'andhra pradesh', NULL, NULL, NULL);
INSERT INTO constituency VALUES ('hindupur', 'andhra pradesh', NULL, NULL, NULL);
INSERT INTO constituency VALUES ('hyderabad', 'andhra pradesh', NULL, NULL, NULL);
INSERT INTO constituency VALUES ('kadapa', 'andhra pradesh', NULL, NULL, NULL);
INSERT INTO constituency VALUES ('kakinada', 'andhra pradesh', NULL, NULL, NULL);
INSERT INTO constituency VALUES ('karimnagar', 'andhra pradesh', NULL, NULL, NULL);
INSERT INTO constituency VALUES ('khammam', 'andhra pradesh', NULL, NULL, NULL);
INSERT INTO constituency VALUES ('kurnool', 'andhra pradesh', NULL, NULL, NULL);
INSERT INTO constituency VALUES ('machilipatnam', 'andhra pradesh', NULL, NULL, NULL);
INSERT INTO constituency VALUES ('mahabubabad', 'andhra pradesh', NULL, NULL, NULL);
INSERT INTO constituency VALUES ('mahabubnagar', 'andhra pradesh', NULL, NULL, NULL);
INSERT INTO constituency VALUES ('mahbubnagar', 'andhra pradesh', NULL, NULL, NULL);
INSERT INTO constituency VALUES ('malkajgiri', 'andhra pradesh', NULL, NULL, NULL);
INSERT INTO constituency VALUES ('medak', 'andhra pradesh', NULL, NULL, NULL);
INSERT INTO constituency VALUES ('miryalguda', 'andhra pradesh', NULL, NULL, NULL);
INSERT INTO constituency VALUES ('nagarkurnool', 'andhra pradesh', NULL, NULL, NULL);
INSERT INTO constituency VALUES ('nalgonda', 'andhra pradesh', NULL, NULL, NULL);
INSERT INTO constituency VALUES ('nandyal', 'andhra pradesh', NULL, NULL, NULL);
INSERT INTO constituency VALUES ('narasapur', 'andhra pradesh', NULL, NULL, NULL);
INSERT INTO constituency VALUES ('narasaraopet', 'andhra pradesh', NULL, NULL, NULL);
INSERT INTO constituency VALUES ('narsapuram', 'andhra pradesh', NULL, NULL, NULL);
INSERT INTO constituency VALUES ('nellore', 'andhra pradesh', NULL, NULL, NULL);
INSERT INTO constituency VALUES ('nizamabad', 'andhra pradesh', NULL, NULL, NULL);
INSERT INTO constituency VALUES ('ongole', 'andhra pradesh', NULL, NULL, NULL);
INSERT INTO constituency VALUES ('parvathipuram', 'andhra pradesh', NULL, NULL, NULL);
INSERT INTO constituency VALUES ('peddapalle', 'andhra pradesh', NULL, NULL, NULL);
INSERT INTO constituency VALUES ('peddapalli', 'andhra pradesh', NULL, NULL, NULL);
INSERT INTO constituency VALUES ('rajahmundry', 'andhra pradesh', NULL, NULL, NULL);
INSERT INTO constituency VALUES ('rajampet', 'andhra pradesh', NULL, NULL, NULL);
INSERT INTO constituency VALUES ('secunderabad', 'andhra pradesh', NULL, NULL, NULL);
INSERT INTO constituency VALUES ('secundrabad', 'andhra pradesh', NULL, NULL, NULL);
INSERT INTO constituency VALUES ('siddipet', 'andhra pradesh', NULL, NULL, NULL);
INSERT INTO constituency VALUES ('srikakulam', 'andhra pradesh', NULL, NULL, NULL);
INSERT INTO constituency VALUES ('tenali', 'andhra pradesh', NULL, NULL, NULL);
INSERT INTO constituency VALUES ('tirupathi', 'andhra pradesh', NULL, NULL, NULL);
INSERT INTO constituency VALUES ('tirupati', 'andhra pradesh', NULL, NULL, NULL);
INSERT INTO constituency VALUES ('vijayawada', 'andhra pradesh', NULL, NULL, NULL);
INSERT INTO constituency VALUES ('visakhapatnam', 'andhra pradesh', NULL, NULL, NULL);
INSERT INTO constituency VALUES ('vizianagaram', 'andhra pradesh', NULL, NULL, NULL);
INSERT INTO constituency VALUES ('warangal', 'andhra pradesh', NULL, NULL, NULL);
INSERT INTO constituency VALUES ('zahirabad', 'andhra pradesh', NULL, NULL, NULL);
INSERT INTO constituency VALUES ('arunachal east', 'arunachal pradesh', NULL, NULL, NULL);
INSERT INTO constituency VALUES ('arunachal west', 'arunachal pradesh', NULL, NULL, NULL);
INSERT INTO constituency VALUES ('autonomous district', 'assam', NULL, NULL, NULL);
INSERT INTO constituency VALUES ('barpeta', 'assam', NULL, NULL, NULL);
INSERT INTO constituency VALUES ('dhubri', 'assam', NULL, NULL, NULL);
INSERT INTO constituency VALUES ('dibrugarh', 'assam', NULL, NULL, NULL);
INSERT INTO constituency VALUES ('gauhati', 'assam', NULL, NULL, NULL);
INSERT INTO constituency VALUES ('jorhat', 'assam', NULL, NULL, NULL);
INSERT INTO constituency VALUES ('kaliabor', 'assam', NULL, NULL, NULL);
INSERT INTO constituency VALUES ('karimganj', 'assam', NULL, NULL, NULL);
INSERT INTO constituency VALUES ('kokrajhar', 'assam', NULL, NULL, NULL);
INSERT INTO constituency VALUES ('lakhimpur', 'assam', NULL, NULL, NULL);
INSERT INTO constituency VALUES ('mangaldoi', 'assam', NULL, NULL, NULL);
INSERT INTO constituency VALUES ('nowgong', 'assam', NULL, NULL, NULL);
INSERT INTO constituency VALUES ('silchar', 'assam', NULL, NULL, NULL);
INSERT INTO constituency VALUES ('tezpur', 'assam', NULL, NULL, NULL);
INSERT INTO constituency VALUES ('araria', 'bihar', NULL, NULL, NULL);
INSERT INTO constituency VALUES ('arrah', 'bihar', NULL, NULL, NULL);
INSERT INTO constituency VALUES ('aurangabad', 'bihar', NULL, NULL, NULL);
INSERT INTO constituency VALUES ('bagaha', 'bihar', NULL, NULL, NULL);
INSERT INTO constituency VALUES ('balia', 'bihar', NULL, NULL, NULL);
INSERT INTO constituency VALUES ('banka', 'bihar', NULL, NULL, NULL);
INSERT INTO constituency VALUES ('barh', 'bihar', NULL, NULL, NULL);
INSERT INTO constituency VALUES ('begusarai', 'bihar', NULL, NULL, NULL);
INSERT INTO constituency VALUES ('bettiah', 'bihar', NULL, NULL, NULL);
INSERT INTO constituency VALUES ('bhagalpur', 'bihar', NULL, NULL, NULL);
INSERT INTO constituency VALUES ('bikramganj', 'bihar', NULL, NULL, NULL);
INSERT INTO constituency VALUES ('buxar', 'bihar', NULL, NULL, NULL);
INSERT INTO constituency VALUES ('chapra', 'bihar', NULL, NULL, NULL);
INSERT INTO constituency VALUES ('chatra', 'bihar', NULL, NULL, NULL);
INSERT INTO constituency VALUES ('darbhanga', 'bihar', NULL, NULL, NULL);
INSERT INTO constituency VALUES ('dhanbad', 'bihar', NULL, NULL, NULL);
INSERT INTO constituency VALUES ('dumka', 'bihar', NULL, NULL, NULL);
INSERT INTO constituency VALUES ('gaya', 'bihar', NULL, NULL, NULL);
INSERT INTO constituency VALUES ('giridih', 'bihar', NULL, NULL, NULL);
INSERT INTO constituency VALUES ('godda', 'bihar', NULL, NULL, NULL);
INSERT INTO constituency VALUES ('gopalganj', 'bihar', NULL, NULL, NULL);
INSERT INTO constituency VALUES ('hajipur', 'bihar', NULL, NULL, NULL);
INSERT INTO constituency VALUES ('hazaribagh', 'bihar', NULL, NULL, NULL);
INSERT INTO constituency VALUES ('jahanabad', 'bihar', NULL, NULL, NULL);
INSERT INTO constituency VALUES ('jamshedpur', 'bihar', NULL, NULL, NULL);
INSERT INTO constituency VALUES ('jamui', 'bihar', NULL, NULL, NULL);
INSERT INTO constituency VALUES ('jhanjharpur', 'bihar', NULL, NULL, NULL);
INSERT INTO constituency VALUES ('karakat', 'bihar', NULL, NULL, NULL);
INSERT INTO constituency VALUES ('katihar', 'bihar', NULL, NULL, NULL);
INSERT INTO constituency VALUES ('khagaria', 'bihar', NULL, NULL, NULL);
INSERT INTO constituency VALUES ('khunti', 'bihar', NULL, NULL, NULL);
INSERT INTO constituency VALUES ('kishanganj', 'bihar', NULL, NULL, NULL);
INSERT INTO constituency VALUES ('kodarma', 'bihar', NULL, NULL, NULL);
INSERT INTO constituency VALUES ('lohardaga', 'bihar', NULL, NULL, NULL);
INSERT INTO constituency VALUES ('madhepura', 'bihar', NULL, NULL, NULL);
INSERT INTO constituency VALUES ('madhubani', 'bihar', NULL, NULL, NULL);
INSERT INTO constituency VALUES ('maharajganj', 'bihar', NULL, NULL, NULL);
INSERT INTO constituency VALUES ('monghyr', 'bihar', NULL, NULL, NULL);
INSERT INTO constituency VALUES ('motihari', 'bihar', NULL, NULL, NULL);
INSERT INTO constituency VALUES ('munger', 'bihar', NULL, NULL, NULL);
INSERT INTO constituency VALUES ('muzaffarpur', 'bihar', NULL, NULL, NULL);
INSERT INTO constituency VALUES ('nalanda', 'bihar', NULL, NULL, NULL);
INSERT INTO constituency VALUES ('nawada', 'bihar', NULL, NULL, NULL);
INSERT INTO constituency VALUES ('palamu', 'bihar', NULL, NULL, NULL);
INSERT INTO constituency VALUES ('paschim champaran', 'bihar', NULL, NULL, NULL);
INSERT INTO constituency VALUES ('pataliputra', 'bihar', NULL, NULL, NULL);
INSERT INTO constituency VALUES ('patna', 'bihar', NULL, NULL, NULL);
INSERT INTO constituency VALUES ('patna sahib', 'bihar', NULL, NULL, NULL);
INSERT INTO constituency VALUES ('purnea', 'bihar', NULL, NULL, NULL);
INSERT INTO constituency VALUES ('purnia', 'bihar', NULL, NULL, NULL);
INSERT INTO constituency VALUES ('purvi champaran', 'bihar', NULL, NULL, NULL);
INSERT INTO constituency VALUES ('rajmahal', 'bihar', NULL, NULL, NULL);
INSERT INTO constituency VALUES ('ranchi', 'bihar', NULL, NULL, NULL);
INSERT INTO constituency VALUES ('rosera', 'bihar', NULL, NULL, NULL);
INSERT INTO constituency VALUES ('saharsa', 'bihar', NULL, NULL, NULL);
INSERT INTO constituency VALUES ('samastipur', 'bihar', NULL, NULL, NULL);
INSERT INTO constituency VALUES ('saran', 'bihar', NULL, NULL, NULL);
INSERT INTO constituency VALUES ('sasaram', 'bihar', NULL, NULL, NULL);
INSERT INTO constituency VALUES ('sheohar', 'bihar', NULL, NULL, NULL);
INSERT INTO constituency VALUES ('singhbhum', 'bihar', NULL, NULL, NULL);
INSERT INTO constituency VALUES ('sitamarhi', 'bihar', NULL, NULL, NULL);
INSERT INTO constituency VALUES ('siwan', 'bihar', NULL, NULL, NULL);
INSERT INTO constituency VALUES ('supaul', 'bihar', NULL, NULL, NULL);
INSERT INTO constituency VALUES ('ujiarpur', 'bihar', NULL, NULL, NULL);
INSERT INTO constituency VALUES ('vaishali', 'bihar', NULL, NULL, NULL);
INSERT INTO constituency VALUES ('valmiki nagar', 'bihar', NULL, NULL, NULL);
INSERT INTO constituency VALUES ('chandigarh', 'chandigarh', NULL, NULL, NULL);
INSERT INTO constituency VALUES ('bastar', 'chattisgarh', NULL, NULL, NULL);
INSERT INTO constituency VALUES ('bilaspur', 'chattisgarh', NULL, NULL, NULL);
INSERT INTO constituency VALUES ('durg', 'chattisgarh', NULL, NULL, NULL);
INSERT INTO constituency VALUES ('janjgir-champa', 'chattisgarh', NULL, NULL, NULL);
INSERT INTO constituency VALUES ('kanker', 'chattisgarh', NULL, NULL, NULL);
INSERT INTO constituency VALUES ('korba', 'chattisgarh', NULL, NULL, NULL);
INSERT INTO constituency VALUES ('mahasamund', 'chattisgarh', NULL, NULL, NULL);
INSERT INTO constituency VALUES ('raigarh', 'chattisgarh', NULL, NULL, NULL);
INSERT INTO constituency VALUES ('raipur', 'chattisgarh', NULL, NULL, NULL);
INSERT INTO constituency VALUES ('rajnandgaon', 'chattisgarh', NULL, NULL, NULL);
INSERT INTO constituency VALUES ('sarguja', 'chattisgarh', NULL, NULL, NULL);
INSERT INTO constituency VALUES ('bastar', 'chhattisgarh', NULL, NULL, NULL);
INSERT INTO constituency VALUES ('bilaspur', 'chhattisgarh', NULL, NULL, NULL);
INSERT INTO constituency VALUES ('durg', 'chhattisgarh', NULL, NULL, NULL);
INSERT INTO constituency VALUES ('janjgir', 'chhattisgarh', NULL, NULL, NULL);
INSERT INTO constituency VALUES ('kanker', 'chhattisgarh', NULL, NULL, NULL);
INSERT INTO constituency VALUES ('mahasamund', 'chhattisgarh', NULL, NULL, NULL);
INSERT INTO constituency VALUES ('raigarh', 'chhattisgarh', NULL, NULL, NULL);
INSERT INTO constituency VALUES ('raipur', 'chhattisgarh', NULL, NULL, NULL);
INSERT INTO constituency VALUES ('rajnandgaon', 'chhattisgarh', NULL, NULL, NULL);
INSERT INTO constituency VALUES ('sarangarh', 'chhattisgarh', NULL, NULL, NULL);
INSERT INTO constituency VALUES ('surguja', 'chhattisgarh', NULL, NULL, NULL);
INSERT INTO constituency VALUES ('dadra & nagar haveli', 'dadra & nagar haveli', NULL, NULL, NULL);
INSERT INTO constituency VALUES ('daman & diu', 'daman & diu', NULL, NULL, NULL);
INSERT INTO constituency VALUES ('daman and diu', 'daman & diu', NULL, NULL, NULL);
INSERT INTO constituency VALUES ('mormugao', 'goa', NULL, NULL, NULL);
INSERT INTO constituency VALUES ('north goa', 'goa', NULL, NULL, NULL);
INSERT INTO constituency VALUES ('panaji', 'goa', NULL, NULL, NULL);
INSERT INTO constituency VALUES ('south goa', 'goa', NULL, NULL, NULL);
INSERT INTO constituency VALUES ('ahmedabad', 'gujarat', NULL, NULL, NULL);
INSERT INTO constituency VALUES ('ahmedabad east', 'gujarat', NULL, NULL, NULL);
INSERT INTO constituency VALUES ('ahmedabad west', 'gujarat', NULL, NULL, NULL);
INSERT INTO constituency VALUES ('amreli', 'gujarat', NULL, NULL, NULL);
INSERT INTO constituency VALUES ('anand', 'gujarat', NULL, NULL, NULL);
INSERT INTO constituency VALUES ('banaskantha', 'gujarat', NULL, NULL, NULL);
INSERT INTO constituency VALUES ('bardoli', 'gujarat', NULL, NULL, NULL);
INSERT INTO constituency VALUES ('baroda', 'gujarat', NULL, NULL, NULL);
INSERT INTO constituency VALUES ('bharuch', 'gujarat', NULL, NULL, NULL);
INSERT INTO constituency VALUES ('bhavnagar', 'gujarat', NULL, NULL, NULL);
INSERT INTO constituency VALUES ('broach', 'gujarat', NULL, NULL, NULL);
INSERT INTO constituency VALUES ('bulsar', 'gujarat', NULL, NULL, NULL);
INSERT INTO constituency VALUES ('chhota udaipur', 'gujarat', NULL, NULL, NULL);
INSERT INTO constituency VALUES ('dahod', 'gujarat', NULL, NULL, NULL);
INSERT INTO constituency VALUES ('dhandhuka', 'gujarat', NULL, NULL, NULL);
INSERT INTO constituency VALUES ('dohad', 'gujarat', NULL, NULL, NULL);
INSERT INTO constituency VALUES ('gandhinagar', 'gujarat', NULL, NULL, NULL);
INSERT INTO constituency VALUES ('godhra', 'gujarat', NULL, NULL, NULL);
INSERT INTO constituency VALUES ('jamnagar', 'gujarat', NULL, NULL, NULL);
INSERT INTO constituency VALUES ('junagadh', 'gujarat', NULL, NULL, NULL);
INSERT INTO constituency VALUES ('kachchh', 'gujarat', NULL, NULL, NULL);
INSERT INTO constituency VALUES ('kaira', 'gujarat', NULL, NULL, NULL);
INSERT INTO constituency VALUES ('kapadvanj', 'gujarat', NULL, NULL, NULL);
INSERT INTO constituency VALUES ('kheda', 'gujarat', NULL, NULL, NULL);
INSERT INTO constituency VALUES ('kutch', 'gujarat', NULL, NULL, NULL);
INSERT INTO constituency VALUES ('mahesana', 'gujarat', NULL, NULL, NULL);
INSERT INTO constituency VALUES ('mandvi', 'gujarat', NULL, NULL, NULL);
INSERT INTO constituency VALUES ('mehsana', 'gujarat', NULL, NULL, NULL);
INSERT INTO constituency VALUES ('navsari', 'gujarat', NULL, NULL, NULL);
INSERT INTO constituency VALUES ('panchmahal', 'gujarat', NULL, NULL, NULL);
INSERT INTO constituency VALUES ('patan', 'gujarat', NULL, NULL, NULL);
INSERT INTO constituency VALUES ('porbandar', 'gujarat', NULL, NULL, NULL);
INSERT INTO constituency VALUES ('rajkot', 'gujarat', NULL, NULL, NULL);
INSERT INTO constituency VALUES ('sabarkantha', 'gujarat', NULL, NULL, NULL);
INSERT INTO constituency VALUES ('surat', 'gujarat', NULL, NULL, NULL);
INSERT INTO constituency VALUES ('surendranagar', 'gujarat', NULL, NULL, NULL);
INSERT INTO constituency VALUES ('vadodara', 'gujarat', NULL, NULL, NULL);
INSERT INTO constituency VALUES ('valsad', 'gujarat', NULL, NULL, NULL);
INSERT INTO constituency VALUES ('ambala', 'haryana', NULL, NULL, NULL);
INSERT INTO constituency VALUES ('bhiwani', 'haryana', NULL, NULL, NULL);
INSERT INTO constituency VALUES ('bhiwani-mahendragarh', 'haryana', NULL, NULL, NULL);
INSERT INTO constituency VALUES ('faridabad', 'haryana', NULL, NULL, NULL);
INSERT INTO constituency VALUES ('gurgaon', 'haryana', NULL, NULL, NULL);
INSERT INTO constituency VALUES ('hisar', 'haryana', NULL, NULL, NULL);
INSERT INTO constituency VALUES ('hissar', 'haryana', NULL, NULL, NULL);
INSERT INTO constituency VALUES ('karnal', 'haryana', NULL, NULL, NULL);
INSERT INTO constituency VALUES ('kurukshetra', 'haryana', NULL, NULL, NULL);
INSERT INTO constituency VALUES ('mahendragarh', 'haryana', NULL, NULL, NULL);
INSERT INTO constituency VALUES ('rohtak', 'haryana', NULL, NULL, NULL);
INSERT INTO constituency VALUES ('sirsa', 'haryana', NULL, NULL, NULL);
INSERT INTO constituency VALUES ('sonepat', 'haryana', NULL, NULL, NULL);
INSERT INTO constituency VALUES ('sonipat', 'haryana', NULL, NULL, NULL);
INSERT INTO constituency VALUES ('hamirpur', 'himachal pradesh', NULL, NULL, NULL);
INSERT INTO constituency VALUES ('kangra', 'himachal pradesh', NULL, NULL, NULL);
INSERT INTO constituency VALUES ('mandi', 'himachal pradesh', NULL, NULL, NULL);
INSERT INTO constituency VALUES ('shimla', 'himachal pradesh', NULL, NULL, NULL);
INSERT INTO constituency VALUES ('simla', 'himachal pradesh', NULL, NULL, NULL);
INSERT INTO constituency VALUES ('anantnag', 'jammu & kashmir', NULL, NULL, NULL);
INSERT INTO constituency VALUES ('baramulla', 'jammu & kashmir', NULL, NULL, NULL);
INSERT INTO constituency VALUES ('jammu', 'jammu & kashmir', NULL, NULL, NULL);
INSERT INTO constituency VALUES ('ladakh', 'jammu & kashmir', NULL, NULL, NULL);
INSERT INTO constituency VALUES ('srinagar', 'jammu & kashmir', NULL, NULL, NULL);
INSERT INTO constituency VALUES ('udhampur', 'jammu & kashmir', NULL, NULL, NULL);
INSERT INTO constituency VALUES ('chatra', 'jharkhand', NULL, NULL, NULL);
INSERT INTO constituency VALUES ('dhanbad', 'jharkhand', NULL, NULL, NULL);
INSERT INTO constituency VALUES ('dumka', 'jharkhand', NULL, NULL, NULL);
INSERT INTO constituency VALUES ('giridih', 'jharkhand', NULL, NULL, NULL);
INSERT INTO constituency VALUES ('godda', 'jharkhand', NULL, NULL, NULL);
INSERT INTO constituency VALUES ('hazaribagh', 'jharkhand', NULL, NULL, NULL);
INSERT INTO constituency VALUES ('jamshedpur', 'jharkhand', NULL, NULL, NULL);
INSERT INTO constituency VALUES ('khunti', 'jharkhand', NULL, NULL, NULL);
INSERT INTO constituency VALUES ('kodarma', 'jharkhand', NULL, NULL, NULL);
INSERT INTO constituency VALUES ('lohardaga', 'jharkhand', NULL, NULL, NULL);
INSERT INTO constituency VALUES ('palamau', 'jharkhand', NULL, NULL, NULL);
INSERT INTO constituency VALUES ('rajmahal', 'jharkhand', NULL, NULL, NULL);
INSERT INTO constituency VALUES ('ranchi', 'jharkhand', NULL, NULL, NULL);
INSERT INTO constituency VALUES ('singhbhum', 'jharkhand', NULL, NULL, NULL);
INSERT INTO constituency VALUES ('bagalkot', 'karnataka', NULL, NULL, NULL);
INSERT INTO constituency VALUES ('bangalore central', 'karnataka', NULL, NULL, NULL);
INSERT INTO constituency VALUES ('bangalore north', 'karnataka', NULL, NULL, NULL);
INSERT INTO constituency VALUES ('bangalore rural', 'karnataka', NULL, NULL, NULL);
INSERT INTO constituency VALUES ('bangalore south', 'karnataka', NULL, NULL, NULL);
INSERT INTO constituency VALUES ('belgaum', 'karnataka', NULL, NULL, NULL);
INSERT INTO constituency VALUES ('bellary', 'karnataka', NULL, NULL, NULL);
INSERT INTO constituency VALUES ('bidar', 'karnataka', NULL, NULL, NULL);
INSERT INTO constituency VALUES ('bijapur', 'karnataka', NULL, NULL, NULL);
INSERT INTO constituency VALUES ('chamarajanagar', 'karnataka', NULL, NULL, NULL);
INSERT INTO constituency VALUES ('chikballapur', 'karnataka', NULL, NULL, NULL);
INSERT INTO constituency VALUES ('chikkballapur', 'karnataka', NULL, NULL, NULL);
INSERT INTO constituency VALUES ('chikkodi', 'karnataka', NULL, NULL, NULL);
INSERT INTO constituency VALUES ('chikmagalur', 'karnataka', NULL, NULL, NULL);
INSERT INTO constituency VALUES ('chitradurga', 'karnataka', NULL, NULL, NULL);
INSERT INTO constituency VALUES ('dakshina kannada', 'karnataka', NULL, NULL, NULL);
INSERT INTO constituency VALUES ('davanagere', 'karnataka', NULL, NULL, NULL);
INSERT INTO constituency VALUES ('davangere', 'karnataka', NULL, NULL, NULL);
INSERT INTO constituency VALUES ('dharwad', 'karnataka', NULL, NULL, NULL);
INSERT INTO constituency VALUES ('dharwad north', 'karnataka', NULL, NULL, NULL);
INSERT INTO constituency VALUES ('dharwad south', 'karnataka', NULL, NULL, NULL);
INSERT INTO constituency VALUES ('gulbarga', 'karnataka', NULL, NULL, NULL);
INSERT INTO constituency VALUES ('hassan', 'karnataka', NULL, NULL, NULL);
INSERT INTO constituency VALUES ('haveri', 'karnataka', NULL, NULL, NULL);
INSERT INTO constituency VALUES ('kanakapura', 'karnataka', NULL, NULL, NULL);
INSERT INTO constituency VALUES ('kanara', 'karnataka', NULL, NULL, NULL);
INSERT INTO constituency VALUES ('kolar', 'karnataka', NULL, NULL, NULL);
INSERT INTO constituency VALUES ('koppal', 'karnataka', NULL, NULL, NULL);
INSERT INTO constituency VALUES ('mandya', 'karnataka', NULL, NULL, NULL);
INSERT INTO constituency VALUES ('mangalore', 'karnataka', NULL, NULL, NULL);
INSERT INTO constituency VALUES ('mysore', 'karnataka', NULL, NULL, NULL);
INSERT INTO constituency VALUES ('raichur', 'karnataka', NULL, NULL, NULL);
INSERT INTO constituency VALUES ('shimoga', 'karnataka', NULL, NULL, NULL);
INSERT INTO constituency VALUES ('tumkur', 'karnataka', NULL, NULL, NULL);
INSERT INTO constituency VALUES ('udupi', 'karnataka', NULL, NULL, NULL);
INSERT INTO constituency VALUES ('udupi chikmagalur', 'karnataka', NULL, NULL, NULL);
INSERT INTO constituency VALUES ('uttara kannada', 'karnataka', NULL, NULL, NULL);
INSERT INTO constituency VALUES ('adoor', 'kerala', NULL, NULL, NULL);
INSERT INTO constituency VALUES ('alappuzha', 'kerala', NULL, NULL, NULL);
INSERT INTO constituency VALUES ('alathur', 'kerala', NULL, NULL, NULL);
INSERT INTO constituency VALUES ('alleppey', 'kerala', NULL, NULL, NULL);
INSERT INTO constituency VALUES ('attingal', 'kerala', NULL, NULL, NULL);
INSERT INTO constituency VALUES ('badagara', 'kerala', NULL, NULL, NULL);
INSERT INTO constituency VALUES ('calicut', 'kerala', NULL, NULL, NULL);
INSERT INTO constituency VALUES ('cannanore', 'kerala', NULL, NULL, NULL);
INSERT INTO constituency VALUES ('chalakudy', 'kerala', NULL, NULL, NULL);
INSERT INTO constituency VALUES ('chirayinkil', 'kerala', NULL, NULL, NULL);
INSERT INTO constituency VALUES ('ernakulam', 'kerala', NULL, NULL, NULL);
INSERT INTO constituency VALUES ('idukki', 'kerala', NULL, NULL, NULL);
INSERT INTO constituency VALUES ('kannur', 'kerala', NULL, NULL, NULL);
INSERT INTO constituency VALUES ('kasaragod', 'kerala', NULL, NULL, NULL);
INSERT INTO constituency VALUES ('kollam', 'kerala', NULL, NULL, NULL);
INSERT INTO constituency VALUES ('kottayam', 'kerala', NULL, NULL, NULL);
INSERT INTO constituency VALUES ('kozhikode', 'kerala', NULL, NULL, NULL);
INSERT INTO constituency VALUES ('malappuram', 'kerala', NULL, NULL, NULL);
INSERT INTO constituency VALUES ('manjeri', 'kerala', NULL, NULL, NULL);
INSERT INTO constituency VALUES ('mavelikara', 'kerala', NULL, NULL, NULL);
INSERT INTO constituency VALUES ('mavelikkara', 'kerala', NULL, NULL, NULL);
INSERT INTO constituency VALUES ('mukundapuram', 'kerala', NULL, NULL, NULL);
INSERT INTO constituency VALUES ('muvattupuzha', 'kerala', NULL, NULL, NULL);
INSERT INTO constituency VALUES ('ottapalam', 'kerala', NULL, NULL, NULL);
INSERT INTO constituency VALUES ('palakkad', 'kerala', NULL, NULL, NULL);
INSERT INTO constituency VALUES ('palghat', 'kerala', NULL, NULL, NULL);
INSERT INTO constituency VALUES ('pathanamthitta', 'kerala', NULL, NULL, NULL);
INSERT INTO constituency VALUES ('ponnani', 'kerala', NULL, NULL, NULL);
INSERT INTO constituency VALUES ('quilon', 'kerala', NULL, NULL, NULL);
INSERT INTO constituency VALUES ('thiruvananthapuram', 'kerala', NULL, NULL, NULL);
INSERT INTO constituency VALUES ('thrissur', 'kerala', NULL, NULL, NULL);
INSERT INTO constituency VALUES ('trichur', 'kerala', NULL, NULL, NULL);
INSERT INTO constituency VALUES ('trivandrum', 'kerala', NULL, NULL, NULL);
INSERT INTO constituency VALUES ('vadakara', 'kerala', NULL, NULL, NULL);
INSERT INTO constituency VALUES ('wayanad', 'kerala', NULL, NULL, NULL);
INSERT INTO constituency VALUES ('lakshadweep', 'lakshadweep', NULL, NULL, NULL);
INSERT INTO constituency VALUES ('balaghat', 'madhya pradesh', NULL, NULL, NULL);
INSERT INTO constituency VALUES ('bastar', 'madhya pradesh', NULL, NULL, NULL);
INSERT INTO constituency VALUES ('betul', 'madhya pradesh', NULL, NULL, NULL);
INSERT INTO constituency VALUES ('bhind', 'madhya pradesh', NULL, NULL, NULL);
INSERT INTO constituency VALUES ('bhopal', 'madhya pradesh', NULL, NULL, NULL);
INSERT INTO constituency VALUES ('bilaspur', 'madhya pradesh', NULL, NULL, NULL);
INSERT INTO constituency VALUES ('chhindwara', 'madhya pradesh', NULL, NULL, NULL);
INSERT INTO constituency VALUES ('damoh', 'madhya pradesh', NULL, NULL, NULL);
INSERT INTO constituency VALUES ('dewas', 'madhya pradesh', NULL, NULL, NULL);
INSERT INTO constituency VALUES ('dhar', 'madhya pradesh', NULL, NULL, NULL);
INSERT INTO constituency VALUES ('durg', 'madhya pradesh', NULL, NULL, NULL);
INSERT INTO constituency VALUES ('guna', 'madhya pradesh', NULL, NULL, NULL);
INSERT INTO constituency VALUES ('gwalior', 'madhya pradesh', NULL, NULL, NULL);
INSERT INTO constituency VALUES ('hoshangabad', 'madhya pradesh', NULL, NULL, NULL);
INSERT INTO constituency VALUES ('indore', 'madhya pradesh', NULL, NULL, NULL);
INSERT INTO constituency VALUES ('jabalpur', 'madhya pradesh', NULL, NULL, NULL);
INSERT INTO constituency VALUES ('janjgir', 'madhya pradesh', NULL, NULL, NULL);
INSERT INTO constituency VALUES ('jhabua', 'madhya pradesh', NULL, NULL, NULL);
INSERT INTO constituency VALUES ('kanker', 'madhya pradesh', NULL, NULL, NULL);
INSERT INTO constituency VALUES ('khajuraho', 'madhya pradesh', NULL, NULL, NULL);
INSERT INTO constituency VALUES ('khandwa', 'madhya pradesh', NULL, NULL, NULL);
INSERT INTO constituency VALUES ('khargone', 'madhya pradesh', NULL, NULL, NULL);
INSERT INTO constituency VALUES ('mahasamund', 'madhya pradesh', NULL, NULL, NULL);
INSERT INTO constituency VALUES ('mandla', 'madhya pradesh', NULL, NULL, NULL);
INSERT INTO constituency VALUES ('mandsaur', 'madhya pradesh', NULL, NULL, NULL);
INSERT INTO constituency VALUES ('mandsour', 'madhya pradesh', NULL, NULL, NULL);
INSERT INTO constituency VALUES ('morena', 'madhya pradesh', NULL, NULL, NULL);
INSERT INTO constituency VALUES ('raigarh', 'madhya pradesh', NULL, NULL, NULL);
INSERT INTO constituency VALUES ('raipur', 'madhya pradesh', NULL, NULL, NULL);
INSERT INTO constituency VALUES ('rajgarh', 'madhya pradesh', NULL, NULL, NULL);
INSERT INTO constituency VALUES ('rajnandgaon', 'madhya pradesh', NULL, NULL, NULL);
INSERT INTO constituency VALUES ('ratlam', 'madhya pradesh', NULL, NULL, NULL);
INSERT INTO constituency VALUES ('rewa', 'madhya pradesh', NULL, NULL, NULL);
INSERT INTO constituency VALUES ('sagar', 'madhya pradesh', NULL, NULL, NULL);
INSERT INTO constituency VALUES ('sarangarh', 'madhya pradesh', NULL, NULL, NULL);
INSERT INTO constituency VALUES ('satna', 'madhya pradesh', NULL, NULL, NULL);
INSERT INTO constituency VALUES ('seoni', 'madhya pradesh', NULL, NULL, NULL);
INSERT INTO constituency VALUES ('shahdol', 'madhya pradesh', NULL, NULL, NULL);
INSERT INTO constituency VALUES ('shajapur', 'madhya pradesh', NULL, NULL, NULL);
INSERT INTO constituency VALUES ('sidhi', 'madhya pradesh', NULL, NULL, NULL);
INSERT INTO constituency VALUES ('surguja', 'madhya pradesh', NULL, NULL, NULL);
INSERT INTO constituency VALUES ('tikamgarh', 'madhya pradesh', NULL, NULL, NULL);
INSERT INTO constituency VALUES ('ujjain', 'madhya pradesh', NULL, NULL, NULL);
INSERT INTO constituency VALUES ('vidisha', 'madhya pradesh', NULL, NULL, NULL);
INSERT INTO constituency VALUES ('ahmadnagar', 'maharashtra', NULL, NULL, NULL);
INSERT INTO constituency VALUES ('ahmednagar', 'maharashtra', NULL, NULL, NULL);
INSERT INTO constituency VALUES ('akola', 'maharashtra', NULL, NULL, NULL);
INSERT INTO constituency VALUES ('amravati', 'maharashtra', NULL, NULL, NULL);
INSERT INTO constituency VALUES ('aurangabad', 'maharashtra', NULL, NULL, NULL);
INSERT INTO constituency VALUES ('baramati', 'maharashtra', NULL, NULL, NULL);
INSERT INTO constituency VALUES ('beed', 'maharashtra', NULL, NULL, NULL);
INSERT INTO constituency VALUES ('bhandara', 'maharashtra', NULL, NULL, NULL);
INSERT INTO constituency VALUES ('bhandara - gondiya', 'maharashtra', NULL, NULL, NULL);
INSERT INTO constituency VALUES ('bhiwandi', 'maharashtra', NULL, NULL, NULL);
INSERT INTO constituency VALUES ('buldhana', 'maharashtra', NULL, NULL, NULL);
INSERT INTO constituency VALUES ('chandrapur', 'maharashtra', NULL, NULL, NULL);
INSERT INTO constituency VALUES ('chimur', 'maharashtra', NULL, NULL, NULL);
INSERT INTO constituency VALUES ('dahanu', 'maharashtra', NULL, NULL, NULL);
INSERT INTO constituency VALUES ('dhule', 'maharashtra', NULL, NULL, NULL);
INSERT INTO constituency VALUES ('dindori', 'maharashtra', NULL, NULL, NULL);
INSERT INTO constituency VALUES ('erandol', 'maharashtra', NULL, NULL, NULL);
INSERT INTO constituency VALUES ('gadchiroli-chimur', 'maharashtra', NULL, NULL, NULL);
INSERT INTO constituency VALUES ('hatkanangle', 'maharashtra', NULL, NULL, NULL);
INSERT INTO constituency VALUES ('hingoli', 'maharashtra', NULL, NULL, NULL);
INSERT INTO constituency VALUES ('ichalkaranji', 'maharashtra', NULL, NULL, NULL);
INSERT INTO constituency VALUES ('jalgaon', 'maharashtra', NULL, NULL, NULL);
INSERT INTO constituency VALUES ('jalna', 'maharashtra', NULL, NULL, NULL);
INSERT INTO constituency VALUES ('kalyan', 'maharashtra', NULL, NULL, NULL);
INSERT INTO constituency VALUES ('karad', 'maharashtra', NULL, NULL, NULL);
INSERT INTO constituency VALUES ('khed', 'maharashtra', NULL, NULL, NULL);
INSERT INTO constituency VALUES ('kolaba', 'maharashtra', NULL, NULL, NULL);
INSERT INTO constituency VALUES ('kolhapur', 'maharashtra', NULL, NULL, NULL);
INSERT INTO constituency VALUES ('kopargaon', 'maharashtra', NULL, NULL, NULL);
INSERT INTO constituency VALUES ('latur', 'maharashtra', NULL, NULL, NULL);
INSERT INTO constituency VALUES ('madha', 'maharashtra', NULL, NULL, NULL);
INSERT INTO constituency VALUES ('malegaon', 'maharashtra', NULL, NULL, NULL);
INSERT INTO constituency VALUES ('maval', 'maharashtra', NULL, NULL, NULL);
INSERT INTO constituency VALUES ('mumbai north', 'maharashtra', NULL, NULL, NULL);
INSERT INTO constituency VALUES ('mumbai north central', 'maharashtra', NULL, NULL, NULL);
INSERT INTO constituency VALUES ('mumbai north east', 'maharashtra', NULL, NULL, NULL);
INSERT INTO constituency VALUES ('mumbai north west', 'maharashtra', NULL, NULL, NULL);
INSERT INTO constituency VALUES ('mumbai south', 'maharashtra', NULL, NULL, NULL);
INSERT INTO constituency VALUES ('mumbai south central', 'maharashtra', NULL, NULL, NULL);
INSERT INTO constituency VALUES ('nagpur', 'maharashtra', NULL, NULL, NULL);
INSERT INTO constituency VALUES ('nanded', 'maharashtra', NULL, NULL, NULL);
INSERT INTO constituency VALUES ('nandurbar', 'maharashtra', NULL, NULL, NULL);
INSERT INTO constituency VALUES ('nashik', 'maharashtra', NULL, NULL, NULL);
INSERT INTO constituency VALUES ('osmanabad', 'maharashtra', NULL, NULL, NULL);
INSERT INTO constituency VALUES ('palghar', 'maharashtra', NULL, NULL, NULL);
INSERT INTO constituency VALUES ('pandharpur', 'maharashtra', NULL, NULL, NULL);
INSERT INTO constituency VALUES ('parbhani', 'maharashtra', NULL, NULL, NULL);
INSERT INTO constituency VALUES ('pune', 'maharashtra', NULL, NULL, NULL);
INSERT INTO constituency VALUES ('raigad', 'maharashtra', NULL, NULL, NULL);
INSERT INTO constituency VALUES ('rajapur', 'maharashtra', NULL, NULL, NULL);
INSERT INTO constituency VALUES ('ramtek', 'maharashtra', NULL, NULL, NULL);
INSERT INTO constituency VALUES ('ratnagiri', 'maharashtra', NULL, NULL, NULL);
INSERT INTO constituency VALUES ('ratnagiri - sindhudurg', 'maharashtra', NULL, NULL, NULL);
INSERT INTO constituency VALUES ('raver', 'maharashtra', NULL, NULL, NULL);
INSERT INTO constituency VALUES ('sangli', 'maharashtra', NULL, NULL, NULL);
INSERT INTO constituency VALUES ('satara', 'maharashtra', NULL, NULL, NULL);
INSERT INTO constituency VALUES ('shirdi', 'maharashtra', NULL, NULL, NULL);
INSERT INTO constituency VALUES ('shirur', 'maharashtra', NULL, NULL, NULL);
INSERT INTO constituency VALUES ('sholapur', 'maharashtra', NULL, NULL, NULL);
INSERT INTO constituency VALUES ('solapur', 'maharashtra', NULL, NULL, NULL);
INSERT INTO constituency VALUES ('thane', 'maharashtra', NULL, NULL, NULL);
INSERT INTO constituency VALUES ('wardha', 'maharashtra', NULL, NULL, NULL);
INSERT INTO constituency VALUES ('washim', 'maharashtra', NULL, NULL, NULL);
INSERT INTO constituency VALUES ('yavatmal', 'maharashtra', NULL, NULL, NULL);
INSERT INTO constituency VALUES ('yavatmal-washim', 'maharashtra', NULL, NULL, NULL);
INSERT INTO constituency VALUES ('inner manipur', 'manipur', NULL, NULL, NULL);
INSERT INTO constituency VALUES ('outer manipur', 'manipur', NULL, NULL, NULL);
INSERT INTO constituency VALUES ('shillong', 'manipur', NULL, NULL, NULL);
INSERT INTO constituency VALUES ('tura', 'manipur', NULL, NULL, NULL);
INSERT INTO constituency VALUES ('shillong', 'meghalaya', NULL, NULL, NULL);
INSERT INTO constituency VALUES ('tura', 'meghalaya', NULL, NULL, NULL);
INSERT INTO constituency VALUES ('mizoram', 'mizoram', NULL, NULL, NULL);
INSERT INTO constituency VALUES ('nagaland', 'nagaland', NULL, NULL, NULL);
INSERT INTO constituency VALUES ('chandni chowk', 'nct of delhi', NULL, NULL, NULL);
INSERT INTO constituency VALUES ('delhi sadar', 'nct of delhi', NULL, NULL, NULL);
INSERT INTO constituency VALUES ('east delhi', 'nct of delhi', NULL, NULL, NULL);
INSERT INTO constituency VALUES ('karol bagh', 'nct of delhi', NULL, NULL, NULL);
INSERT INTO constituency VALUES ('new delhi', 'nct of delhi', NULL, NULL, NULL);
INSERT INTO constituency VALUES ('north east delhi', 'nct of delhi', NULL, NULL, NULL);
INSERT INTO constituency VALUES ('north west delhi', 'nct of delhi', NULL, NULL, NULL);
INSERT INTO constituency VALUES ('outer delhi', 'nct of delhi', NULL, NULL, NULL);
INSERT INTO constituency VALUES ('south delhi', 'nct of delhi', NULL, NULL, NULL);
INSERT INTO constituency VALUES ('west delhi', 'nct of delhi', NULL, NULL, NULL);
INSERT INTO constituency VALUES ('aska', 'orissa', NULL, NULL, NULL);
INSERT INTO constituency VALUES ('balasore', 'orissa', NULL, NULL, NULL);
INSERT INTO constituency VALUES ('bargarh', 'orissa', NULL, NULL, NULL);
INSERT INTO constituency VALUES ('berhampur', 'orissa', NULL, NULL, NULL);
INSERT INTO constituency VALUES ('bhadrak', 'orissa', NULL, NULL, NULL);
INSERT INTO constituency VALUES ('bhubaneswar', 'orissa', NULL, NULL, NULL);
INSERT INTO constituency VALUES ('bolangir', 'orissa', NULL, NULL, NULL);
INSERT INTO constituency VALUES ('cuttack', 'orissa', NULL, NULL, NULL);
INSERT INTO constituency VALUES ('deogarh', 'orissa', NULL, NULL, NULL);
INSERT INTO constituency VALUES ('dhenkanal', 'orissa', NULL, NULL, NULL);
INSERT INTO constituency VALUES ('jagatsinghpur', 'orissa', NULL, NULL, NULL);
INSERT INTO constituency VALUES ('jajpur', 'orissa', NULL, NULL, NULL);
INSERT INTO constituency VALUES ('kalahandi', 'orissa', NULL, NULL, NULL);
INSERT INTO constituency VALUES ('kandhamal', 'orissa', NULL, NULL, NULL);
INSERT INTO constituency VALUES ('kendrapara', 'orissa', NULL, NULL, NULL);
INSERT INTO constituency VALUES ('keonjhar', 'orissa', NULL, NULL, NULL);
INSERT INTO constituency VALUES ('koraput', 'orissa', NULL, NULL, NULL);
INSERT INTO constituency VALUES ('mayurbhanj', 'orissa', NULL, NULL, NULL);
INSERT INTO constituency VALUES ('nabarangpur', 'orissa', NULL, NULL, NULL);
INSERT INTO constituency VALUES ('nowrangpur', 'orissa', NULL, NULL, NULL);
INSERT INTO constituency VALUES ('phulbani', 'orissa', NULL, NULL, NULL);
INSERT INTO constituency VALUES ('puri', 'orissa', NULL, NULL, NULL);
INSERT INTO constituency VALUES ('sambalpur', 'orissa', NULL, NULL, NULL);
INSERT INTO constituency VALUES ('sundargarh', 'orissa', NULL, NULL, NULL);
INSERT INTO constituency VALUES ('puducherry', 'puducherry', NULL, NULL, NULL);
INSERT INTO constituency VALUES ('amritsar', 'punjab', NULL, NULL, NULL);
INSERT INTO constituency VALUES ('anandpur sahib', 'punjab', NULL, NULL, NULL);
INSERT INTO constituency VALUES ('bathinda', 'punjab', NULL, NULL, NULL);
INSERT INTO constituency VALUES ('bhatinda', 'punjab', NULL, NULL, NULL);
INSERT INTO constituency VALUES ('faridkot', 'punjab', NULL, NULL, NULL);
INSERT INTO constituency VALUES ('fatehgarh sahib', 'punjab', NULL, NULL, NULL);
INSERT INTO constituency VALUES ('ferozepur', 'punjab', NULL, NULL, NULL);
INSERT INTO constituency VALUES ('ferozpur', 'punjab', NULL, NULL, NULL);
INSERT INTO constituency VALUES ('gurdaspur', 'punjab', NULL, NULL, NULL);
INSERT INTO constituency VALUES ('hoshiarpur', 'punjab', NULL, NULL, NULL);
INSERT INTO constituency VALUES ('jalandhar', 'punjab', NULL, NULL, NULL);
INSERT INTO constituency VALUES ('jullundur', 'punjab', NULL, NULL, NULL);
INSERT INTO constituency VALUES ('khadoor sahib', 'punjab', NULL, NULL, NULL);
INSERT INTO constituency VALUES ('ludhiana', 'punjab', NULL, NULL, NULL);
INSERT INTO constituency VALUES ('patiala', 'punjab', NULL, NULL, NULL);
INSERT INTO constituency VALUES ('phillaur', 'punjab', NULL, NULL, NULL);
INSERT INTO constituency VALUES ('ropar', 'punjab', NULL, NULL, NULL);
INSERT INTO constituency VALUES ('sangrur', 'punjab', NULL, NULL, NULL);
INSERT INTO constituency VALUES ('tarn taran', 'punjab', NULL, NULL, NULL);
INSERT INTO constituency VALUES ('ajmer', 'rajasthan', NULL, NULL, NULL);
INSERT INTO constituency VALUES ('alwar', 'rajasthan', NULL, NULL, NULL);
INSERT INTO constituency VALUES ('banswara', 'rajasthan', NULL, NULL, NULL);
INSERT INTO constituency VALUES ('barmer', 'rajasthan', NULL, NULL, NULL);
INSERT INTO constituency VALUES ('bayana', 'rajasthan', NULL, NULL, NULL);
INSERT INTO constituency VALUES ('bharatpur', 'rajasthan', NULL, NULL, NULL);
INSERT INTO constituency VALUES ('bhilwara', 'rajasthan', NULL, NULL, NULL);
INSERT INTO constituency VALUES ('bikaner', 'rajasthan', NULL, NULL, NULL);
INSERT INTO constituency VALUES ('chittorgarh', 'rajasthan', NULL, NULL, NULL);
INSERT INTO constituency VALUES ('churu', 'rajasthan', NULL, NULL, NULL);
INSERT INTO constituency VALUES ('dausa', 'rajasthan', NULL, NULL, NULL);
INSERT INTO constituency VALUES ('ganganagar', 'rajasthan', NULL, NULL, NULL);
INSERT INTO constituency VALUES ('jaipur', 'rajasthan', NULL, NULL, NULL);
INSERT INTO constituency VALUES ('jaipur rural', 'rajasthan', NULL, NULL, NULL);
INSERT INTO constituency VALUES ('jalore', 'rajasthan', NULL, NULL, NULL);
INSERT INTO constituency VALUES ('jhalawar', 'rajasthan', NULL, NULL, NULL);
INSERT INTO constituency VALUES ('jhalawar-baran', 'rajasthan', NULL, NULL, NULL);
INSERT INTO constituency VALUES ('jhunjhunu', 'rajasthan', NULL, NULL, NULL);
INSERT INTO constituency VALUES ('jodhpur', 'rajasthan', NULL, NULL, NULL);
INSERT INTO constituency VALUES ('karauli-dholpur', 'rajasthan', NULL, NULL, NULL);
INSERT INTO constituency VALUES ('kota', 'rajasthan', NULL, NULL, NULL);
INSERT INTO constituency VALUES ('nagaur', 'rajasthan', NULL, NULL, NULL);
INSERT INTO constituency VALUES ('pali', 'rajasthan', NULL, NULL, NULL);
INSERT INTO constituency VALUES ('rajsamand', 'rajasthan', NULL, NULL, NULL);
INSERT INTO constituency VALUES ('salumber', 'rajasthan', NULL, NULL, NULL);
INSERT INTO constituency VALUES ('sawai madhopur', 'rajasthan', NULL, NULL, NULL);
INSERT INTO constituency VALUES ('sikar', 'rajasthan', NULL, NULL, NULL);
INSERT INTO constituency VALUES ('tonk', 'rajasthan', NULL, NULL, NULL);
INSERT INTO constituency VALUES ('tonk-sawai madhopur', 'rajasthan', NULL, NULL, NULL);
INSERT INTO constituency VALUES ('udaipur', 'rajasthan', NULL, NULL, NULL);
INSERT INTO constituency VALUES ('sikkim', 'sikkim', NULL, NULL, NULL);
INSERT INTO constituency VALUES ('arakkonam', 'tamil nadu', NULL, NULL, NULL);
INSERT INTO constituency VALUES ('arani', 'tamil nadu', NULL, NULL, NULL);
INSERT INTO constituency VALUES ('chengalpattu', 'tamil nadu', NULL, NULL, NULL);
INSERT INTO constituency VALUES ('chennai central', 'tamil nadu', NULL, NULL, NULL);
INSERT INTO constituency VALUES ('chennai north', 'tamil nadu', NULL, NULL, NULL);
INSERT INTO constituency VALUES ('chennai south', 'tamil nadu', NULL, NULL, NULL);
INSERT INTO constituency VALUES ('chidambaram', 'tamil nadu', NULL, NULL, NULL);
INSERT INTO constituency VALUES ('coimbatore', 'tamil nadu', NULL, NULL, NULL);
INSERT INTO constituency VALUES ('cuddalore', 'tamil nadu', NULL, NULL, NULL);
INSERT INTO constituency VALUES ('dharmapuri', 'tamil nadu', NULL, NULL, NULL);
INSERT INTO constituency VALUES ('dindigul', 'tamil nadu', NULL, NULL, NULL);
INSERT INTO constituency VALUES ('erode', 'tamil nadu', NULL, NULL, NULL);
INSERT INTO constituency VALUES ('gobichettipalayam', 'tamil nadu', NULL, NULL, NULL);
INSERT INTO constituency VALUES ('kallakurichi', 'tamil nadu', NULL, NULL, NULL);
INSERT INTO constituency VALUES ('kancheepuram', 'tamil nadu', NULL, NULL, NULL);
INSERT INTO constituency VALUES ('kanniyakumari', 'tamil nadu', NULL, NULL, NULL);
INSERT INTO constituency VALUES ('karur', 'tamil nadu', NULL, NULL, NULL);
INSERT INTO constituency VALUES ('krishnagiri', 'tamil nadu', NULL, NULL, NULL);
INSERT INTO constituency VALUES ('madras central', 'tamil nadu', NULL, NULL, NULL);
INSERT INTO constituency VALUES ('madras north', 'tamil nadu', NULL, NULL, NULL);
INSERT INTO constituency VALUES ('madras south', 'tamil nadu', NULL, NULL, NULL);
INSERT INTO constituency VALUES ('madurai', 'tamil nadu', NULL, NULL, NULL);
INSERT INTO constituency VALUES ('mayiladuthurai', 'tamil nadu', NULL, NULL, NULL);
INSERT INTO constituency VALUES ('mayiladuturai', 'tamil nadu', NULL, NULL, NULL);
INSERT INTO constituency VALUES ('nagapattinam', 'tamil nadu', NULL, NULL, NULL);
INSERT INTO constituency VALUES ('nagercoil', 'tamil nadu', NULL, NULL, NULL);
INSERT INTO constituency VALUES ('namakkal', 'tamil nadu', NULL, NULL, NULL);
INSERT INTO constituency VALUES ('nilgiris', 'tamil nadu', NULL, NULL, NULL);
INSERT INTO constituency VALUES ('palani', 'tamil nadu', NULL, NULL, NULL);
INSERT INTO constituency VALUES ('perambalur', 'tamil nadu', NULL, NULL, NULL);
INSERT INTO constituency VALUES ('periyakulam', 'tamil nadu', NULL, NULL, NULL);
INSERT INTO constituency VALUES ('pollachi', 'tamil nadu', NULL, NULL, NULL);
INSERT INTO constituency VALUES ('pudukkottai', 'tamil nadu', NULL, NULL, NULL);
INSERT INTO constituency VALUES ('ramanathapuram', 'tamil nadu', NULL, NULL, NULL);
INSERT INTO constituency VALUES ('rasipuram', 'tamil nadu', NULL, NULL, NULL);
INSERT INTO constituency VALUES ('salem', 'tamil nadu', NULL, NULL, NULL);
INSERT INTO constituency VALUES ('sivaganga', 'tamil nadu', NULL, NULL, NULL);
INSERT INTO constituency VALUES ('sivakasi', 'tamil nadu', NULL, NULL, NULL);
INSERT INTO constituency VALUES ('sriperumbudur', 'tamil nadu', NULL, NULL, NULL);
INSERT INTO constituency VALUES ('tenkasi', 'tamil nadu', NULL, NULL, NULL);
INSERT INTO constituency VALUES ('thanjavur', 'tamil nadu', NULL, NULL, NULL);
INSERT INTO constituency VALUES ('theni', 'tamil nadu', NULL, NULL, NULL);
INSERT INTO constituency VALUES ('thiruvallur', 'tamil nadu', NULL, NULL, NULL);
INSERT INTO constituency VALUES ('thoothukkudi', 'tamil nadu', NULL, NULL, NULL);
INSERT INTO constituency VALUES ('tindivanam', 'tamil nadu', NULL, NULL, NULL);
INSERT INTO constituency VALUES ('tiruchendur', 'tamil nadu', NULL, NULL, NULL);
INSERT INTO constituency VALUES ('tiruchengode', 'tamil nadu', NULL, NULL, NULL);
INSERT INTO constituency VALUES ('tiruchirappalli', 'tamil nadu', NULL, NULL, NULL);
INSERT INTO constituency VALUES ('tirunelveli', 'tamil nadu', NULL, NULL, NULL);
INSERT INTO constituency VALUES ('tiruppattur', 'tamil nadu', NULL, NULL, NULL);
INSERT INTO constituency VALUES ('tiruppur', 'tamil nadu', NULL, NULL, NULL);
INSERT INTO constituency VALUES ('tiruvannamalai', 'tamil nadu', NULL, NULL, NULL);
INSERT INTO constituency VALUES ('vandavasi', 'tamil nadu', NULL, NULL, NULL);
INSERT INTO constituency VALUES ('vellore', 'tamil nadu', NULL, NULL, NULL);
INSERT INTO constituency VALUES ('viluppuram', 'tamil nadu', NULL, NULL, NULL);
INSERT INTO constituency VALUES ('virudhunagar', 'tamil nadu', NULL, NULL, NULL);
INSERT INTO constituency VALUES ('tripura east', 'tripura', NULL, NULL, NULL);
INSERT INTO constituency VALUES ('tripura west', 'tripura', NULL, NULL, NULL);
INSERT INTO constituency VALUES ('agra', 'uttar pradesh', NULL, NULL, NULL);
INSERT INTO constituency VALUES ('akbarpur', 'uttar pradesh', NULL, NULL, NULL);
INSERT INTO constituency VALUES ('aligarh', 'uttar pradesh', NULL, NULL, NULL);
INSERT INTO constituency VALUES ('allahabad', 'uttar pradesh', NULL, NULL, NULL);
INSERT INTO constituency VALUES ('almora', 'uttar pradesh', NULL, NULL, NULL);
INSERT INTO constituency VALUES ('ambedkar nagar', 'uttar pradesh', NULL, NULL, NULL);
INSERT INTO constituency VALUES ('amethi', 'uttar pradesh', NULL, NULL, NULL);
INSERT INTO constituency VALUES ('amroha', 'uttar pradesh', NULL, NULL, NULL);
INSERT INTO constituency VALUES ('aonla', 'uttar pradesh', NULL, NULL, NULL);
INSERT INTO constituency VALUES ('azamgarh', 'uttar pradesh', NULL, NULL, NULL);
INSERT INTO constituency VALUES ('badaun', 'uttar pradesh', NULL, NULL, NULL);
INSERT INTO constituency VALUES ('baghpat', 'uttar pradesh', NULL, NULL, NULL);
INSERT INTO constituency VALUES ('bahraich', 'uttar pradesh', NULL, NULL, NULL);
INSERT INTO constituency VALUES ('ballia', 'uttar pradesh', NULL, NULL, NULL);
INSERT INTO constituency VALUES ('balrampur', 'uttar pradesh', NULL, NULL, NULL);
INSERT INTO constituency VALUES ('banda', 'uttar pradesh', NULL, NULL, NULL);
INSERT INTO constituency VALUES ('bansgaon', 'uttar pradesh', NULL, NULL, NULL);
INSERT INTO constituency VALUES ('bara banki', 'uttar pradesh', NULL, NULL, NULL);
INSERT INTO constituency VALUES ('barabanki', 'uttar pradesh', NULL, NULL, NULL);
INSERT INTO constituency VALUES ('bareilly', 'uttar pradesh', NULL, NULL, NULL);
INSERT INTO constituency VALUES ('basti', 'uttar pradesh', NULL, NULL, NULL);
INSERT INTO constituency VALUES ('bhadohi', 'uttar pradesh', NULL, NULL, NULL);
INSERT INTO constituency VALUES ('bijnor', 'uttar pradesh', NULL, NULL, NULL);
INSERT INTO constituency VALUES ('bilhaur', 'uttar pradesh', NULL, NULL, NULL);
INSERT INTO constituency VALUES ('budaun', 'uttar pradesh', NULL, NULL, NULL);
INSERT INTO constituency VALUES ('bulandshahr', 'uttar pradesh', NULL, NULL, NULL);
INSERT INTO constituency VALUES ('chail', 'uttar pradesh', NULL, NULL, NULL);
INSERT INTO constituency VALUES ('chandauli', 'uttar pradesh', NULL, NULL, NULL);
INSERT INTO constituency VALUES ('deoria', 'uttar pradesh', NULL, NULL, NULL);
INSERT INTO constituency VALUES ('dhaurahra', 'uttar pradesh', NULL, NULL, NULL);
INSERT INTO constituency VALUES ('domariaganj', 'uttar pradesh', NULL, NULL, NULL);
INSERT INTO constituency VALUES ('domariyaganj', 'uttar pradesh', NULL, NULL, NULL);
INSERT INTO constituency VALUES ('etah', 'uttar pradesh', NULL, NULL, NULL);
INSERT INTO constituency VALUES ('etawah', 'uttar pradesh', NULL, NULL, NULL);
INSERT INTO constituency VALUES ('faizabad', 'uttar pradesh', NULL, NULL, NULL);
INSERT INTO constituency VALUES ('farrukhabad', 'uttar pradesh', NULL, NULL, NULL);
INSERT INTO constituency VALUES ('fatehpur', 'uttar pradesh', NULL, NULL, NULL);
INSERT INTO constituency VALUES ('fatehpur sikri', 'uttar pradesh', NULL, NULL, NULL);
INSERT INTO constituency VALUES ('firozabad', 'uttar pradesh', NULL, NULL, NULL);
INSERT INTO constituency VALUES ('garhwal', 'uttar pradesh', NULL, NULL, NULL);
INSERT INTO constituency VALUES ('gautam buddh nagar', 'uttar pradesh', NULL, NULL, NULL);
INSERT INTO constituency VALUES ('ghatampur', 'uttar pradesh', NULL, NULL, NULL);
INSERT INTO constituency VALUES ('ghaziabad', 'uttar pradesh', NULL, NULL, NULL);
INSERT INTO constituency VALUES ('ghazipur', 'uttar pradesh', NULL, NULL, NULL);
INSERT INTO constituency VALUES ('ghosi', 'uttar pradesh', NULL, NULL, NULL);
INSERT INTO constituency VALUES ('gonda', 'uttar pradesh', NULL, NULL, NULL);
INSERT INTO constituency VALUES ('gorakhpur', 'uttar pradesh', NULL, NULL, NULL);
INSERT INTO constituency VALUES ('hamirpur', 'uttar pradesh', NULL, NULL, NULL);
INSERT INTO constituency VALUES ('hapur', 'uttar pradesh', NULL, NULL, NULL);
INSERT INTO constituency VALUES ('hardoi', 'uttar pradesh', NULL, NULL, NULL);
INSERT INTO constituency VALUES ('hardwar', 'uttar pradesh', NULL, NULL, NULL);
INSERT INTO constituency VALUES ('hathras', 'uttar pradesh', NULL, NULL, NULL);
INSERT INTO constituency VALUES ('jalaun', 'uttar pradesh', NULL, NULL, NULL);
INSERT INTO constituency VALUES ('jalesar', 'uttar pradesh', NULL, NULL, NULL);
INSERT INTO constituency VALUES ('jaunpur', 'uttar pradesh', NULL, NULL, NULL);
INSERT INTO constituency VALUES ('jhansi', 'uttar pradesh', NULL, NULL, NULL);
INSERT INTO constituency VALUES ('kairana', 'uttar pradesh', NULL, NULL, NULL);
INSERT INTO constituency VALUES ('kaiserganj', 'uttar pradesh', NULL, NULL, NULL);
INSERT INTO constituency VALUES ('kannauj', 'uttar pradesh', NULL, NULL, NULL);
INSERT INTO constituency VALUES ('kanpur', 'uttar pradesh', NULL, NULL, NULL);
INSERT INTO constituency VALUES ('kaushambi', 'uttar pradesh', NULL, NULL, NULL);
INSERT INTO constituency VALUES ('khalilabad', 'uttar pradesh', NULL, NULL, NULL);
INSERT INTO constituency VALUES ('kheri', 'uttar pradesh', NULL, NULL, NULL);
INSERT INTO constituency VALUES ('khurja', 'uttar pradesh', NULL, NULL, NULL);
INSERT INTO constituency VALUES ('kushi nagar', 'uttar pradesh', NULL, NULL, NULL);
INSERT INTO constituency VALUES ('lalganj', 'uttar pradesh', NULL, NULL, NULL);
INSERT INTO constituency VALUES ('lucknow', 'uttar pradesh', NULL, NULL, NULL);
INSERT INTO constituency VALUES ('machhlishahr', 'uttar pradesh', NULL, NULL, NULL);
INSERT INTO constituency VALUES ('maharajganj', 'uttar pradesh', NULL, NULL, NULL);
INSERT INTO constituency VALUES ('mainpuri', 'uttar pradesh', NULL, NULL, NULL);
INSERT INTO constituency VALUES ('mathura', 'uttar pradesh', NULL, NULL, NULL);
INSERT INTO constituency VALUES ('meerut', 'uttar pradesh', NULL, NULL, NULL);
INSERT INTO constituency VALUES ('mirzapur', 'uttar pradesh', NULL, NULL, NULL);
INSERT INTO constituency VALUES ('misrikh', 'uttar pradesh', NULL, NULL, NULL);
INSERT INTO constituency VALUES ('mohanlalganj', 'uttar pradesh', NULL, NULL, NULL);
INSERT INTO constituency VALUES ('moradabad', 'uttar pradesh', NULL, NULL, NULL);
INSERT INTO constituency VALUES ('muzaffarnagar', 'uttar pradesh', NULL, NULL, NULL);
INSERT INTO constituency VALUES ('nagina', 'uttar pradesh', NULL, NULL, NULL);
INSERT INTO constituency VALUES ('nainital', 'uttar pradesh', NULL, NULL, NULL);
INSERT INTO constituency VALUES ('padrauna', 'uttar pradesh', NULL, NULL, NULL);
INSERT INTO constituency VALUES ('phulpur', 'uttar pradesh', NULL, NULL, NULL);
INSERT INTO constituency VALUES ('pilibhit', 'uttar pradesh', NULL, NULL, NULL);
INSERT INTO constituency VALUES ('pratapgarh', 'uttar pradesh', NULL, NULL, NULL);
INSERT INTO constituency VALUES ('rae bareli', 'uttar pradesh', NULL, NULL, NULL);
INSERT INTO constituency VALUES ('rampur', 'uttar pradesh', NULL, NULL, NULL);
INSERT INTO constituency VALUES ('robertsganj', 'uttar pradesh', NULL, NULL, NULL);
INSERT INTO constituency VALUES ('saharanpur', 'uttar pradesh', NULL, NULL, NULL);
INSERT INTO constituency VALUES ('saidpur', 'uttar pradesh', NULL, NULL, NULL);
INSERT INTO constituency VALUES ('salempur', 'uttar pradesh', NULL, NULL, NULL);
INSERT INTO constituency VALUES ('sambhal', 'uttar pradesh', NULL, NULL, NULL);
INSERT INTO constituency VALUES ('sant kabir nagar', 'uttar pradesh', NULL, NULL, NULL);
INSERT INTO constituency VALUES ('shahabad', 'uttar pradesh', NULL, NULL, NULL);
INSERT INTO constituency VALUES ('shahjahanpur', 'uttar pradesh', NULL, NULL, NULL);
INSERT INTO constituency VALUES ('shrawasti', 'uttar pradesh', NULL, NULL, NULL);
INSERT INTO constituency VALUES ('sitapur', 'uttar pradesh', NULL, NULL, NULL);
INSERT INTO constituency VALUES ('sultanpur', 'uttar pradesh', NULL, NULL, NULL);
INSERT INTO constituency VALUES ('tehri garhwal', 'uttar pradesh', NULL, NULL, NULL);
INSERT INTO constituency VALUES ('unnao', 'uttar pradesh', NULL, NULL, NULL);
INSERT INTO constituency VALUES ('varanasi', 'uttar pradesh', NULL, NULL, NULL);
INSERT INTO constituency VALUES ('almora', 'uttarakhand', NULL, NULL, NULL);
INSERT INTO constituency VALUES ('garhwal', 'uttarakhand', NULL, NULL, NULL);
INSERT INTO constituency VALUES ('hardwar', 'uttarakhand', NULL, NULL, NULL);
INSERT INTO constituency VALUES ('nainital', 'uttarakhand', NULL, NULL, NULL);
INSERT INTO constituency VALUES ('nainital-udhamsingh nagar', 'uttarakhand', NULL, NULL, NULL);
INSERT INTO constituency VALUES ('tehri garhwal', 'uttarakhand', NULL, NULL, NULL);
INSERT INTO constituency VALUES ('alipurduars', 'west bengal', NULL, NULL, NULL);
INSERT INTO constituency VALUES ('arambagh', 'west bengal', NULL, NULL, NULL);
INSERT INTO constituency VALUES ('asansol', 'west bengal', NULL, NULL, NULL);
INSERT INTO constituency VALUES ('baharampur', 'west bengal', NULL, NULL, NULL);
INSERT INTO constituency VALUES ('balurghat', 'west bengal', NULL, NULL, NULL);
INSERT INTO constituency VALUES ('bangaon', 'west bengal', NULL, NULL, NULL);
INSERT INTO constituency VALUES ('bankura', 'west bengal', NULL, NULL, NULL);
INSERT INTO constituency VALUES ('barasat', 'west bengal', NULL, NULL, NULL);
INSERT INTO constituency VALUES ('bardhaman purba', 'west bengal', NULL, NULL, NULL);
INSERT INTO constituency VALUES ('barrackpore', 'west bengal', NULL, NULL, NULL);
INSERT INTO constituency VALUES ('basirhat', 'west bengal', NULL, NULL, NULL);
INSERT INTO constituency VALUES ('berhampore', 'west bengal', NULL, NULL, NULL);
INSERT INTO constituency VALUES ('birbhum', 'west bengal', NULL, NULL, NULL);
INSERT INTO constituency VALUES ('bishnupur', 'west bengal', NULL, NULL, NULL);
INSERT INTO constituency VALUES ('bolpur', 'west bengal', NULL, NULL, NULL);
INSERT INTO constituency VALUES ('burdwan', 'west bengal', NULL, NULL, NULL);
INSERT INTO constituency VALUES ('burdwan - durgapur', 'west bengal', NULL, NULL, NULL);
INSERT INTO constituency VALUES ('calcutta north east', 'west bengal', NULL, NULL, NULL);
INSERT INTO constituency VALUES ('calcutta north west', 'west bengal', NULL, NULL, NULL);
INSERT INTO constituency VALUES ('calcutta south', 'west bengal', NULL, NULL, NULL);
INSERT INTO constituency VALUES ('contai', 'west bengal', NULL, NULL, NULL);
INSERT INTO constituency VALUES ('cooch behar', 'west bengal', NULL, NULL, NULL);
INSERT INTO constituency VALUES ('darjeeling', 'west bengal', NULL, NULL, NULL);
INSERT INTO constituency VALUES ('diamond harbour', 'west bengal', NULL, NULL, NULL);
INSERT INTO constituency VALUES ('dum dum', 'west bengal', NULL, NULL, NULL);
INSERT INTO constituency VALUES ('durgapur', 'west bengal', NULL, NULL, NULL);
INSERT INTO constituency VALUES ('ghatal', 'west bengal', NULL, NULL, NULL);
INSERT INTO constituency VALUES ('hooghly', 'west bengal', NULL, NULL, NULL);
INSERT INTO constituency VALUES ('howrah', 'west bengal', NULL, NULL, NULL);
INSERT INTO constituency VALUES ('jadavpur', 'west bengal', NULL, NULL, NULL);
INSERT INTO constituency VALUES ('jalpaiguri', 'west bengal', NULL, NULL, NULL);
INSERT INTO constituency VALUES ('jangipur', 'west bengal', NULL, NULL, NULL);
INSERT INTO constituency VALUES ('jhargram', 'west bengal', NULL, NULL, NULL);
INSERT INTO constituency VALUES ('joynagar', 'west bengal', NULL, NULL, NULL);
INSERT INTO constituency VALUES ('kanthi', 'west bengal', NULL, NULL, NULL);
INSERT INTO constituency VALUES ('katwa', 'west bengal', NULL, NULL, NULL);
INSERT INTO constituency VALUES ('kolkata dakshin', 'west bengal', NULL, NULL, NULL);
INSERT INTO constituency VALUES ('kolkata uttar', 'west bengal', NULL, NULL, NULL);
INSERT INTO constituency VALUES ('krishnagar', 'west bengal', NULL, NULL, NULL);
INSERT INTO constituency VALUES ('krishnanagar', 'west bengal', NULL, NULL, NULL);
INSERT INTO constituency VALUES ('malda', 'west bengal', NULL, NULL, NULL);
INSERT INTO constituency VALUES ('maldaha dakshin', 'west bengal', NULL, NULL, NULL);
INSERT INTO constituency VALUES ('maldaha uttar', 'west bengal', NULL, NULL, NULL);
INSERT INTO constituency VALUES ('mathurapur', 'west bengal', NULL, NULL, NULL);
INSERT INTO constituency VALUES ('medinipur', 'west bengal', NULL, NULL, NULL);
INSERT INTO constituency VALUES ('midnapore', 'west bengal', NULL, NULL, NULL);
INSERT INTO constituency VALUES ('murshidabad', 'west bengal', NULL, NULL, NULL);
INSERT INTO constituency VALUES ('nabadwip', 'west bengal', NULL, NULL, NULL);
INSERT INTO constituency VALUES ('panskura', 'west bengal', NULL, NULL, NULL);
INSERT INTO constituency VALUES ('purulia', 'west bengal', NULL, NULL, NULL);
INSERT INTO constituency VALUES ('raiganj', 'west bengal', NULL, NULL, NULL);
INSERT INTO constituency VALUES ('ranaghat', 'west bengal', NULL, NULL, NULL);
INSERT INTO constituency VALUES ('serampore', 'west bengal', NULL, NULL, NULL);
INSERT INTO constituency VALUES ('srerampur', 'west bengal', NULL, NULL, NULL);
INSERT INTO constituency VALUES ('tamluk', 'west bengal', NULL, NULL, NULL);
INSERT INTO constituency VALUES ('uluberia', 'west bengal', NULL, NULL, NULL);
INSERT INTO constituency VALUES ('vishnupur', 'west bengal', NULL, NULL, NULL);
