INSERT INTO party VALUES ('akhand bharti', NULL, NULL, 0, TRUE, NULL, NULL, NULL, NULL);
INSERT INTO party VALUES ('akhil bharatiya ashok sena', NULL, NULL, 0, TRUE, NULL, NULL, NULL, NULL);
INSERT INTO party VALUES ('akhil bharatiya bhrastachar nirmoolan sena', NULL, NULL, 0, TRUE, NULL, NULL, NULL, NULL);
INSERT INTO party VALUES ('akhil bhartiya berozgaar party', NULL, NULL, 0, TRUE, NULL, NULL, NULL, NULL);
INSERT INTO party VALUES ('akhil bharatiya congress dal (ambedkar)', NULL, NULL, 0, TRUE, NULL, NULL, NULL, NULL);
INSERT INTO party VALUES ('akhil bharatiya desh bhakt morcha', NULL, NULL, 0, TRUE, NULL, NULL, NULL, NULL);
INSERT INTO party VALUES ('akhil bharatiya general labour party', NULL, NULL, 0, TRUE, NULL, NULL, NULL, NULL);
INSERT INTO party VALUES ('akhil bharatiya garib mazdoor kisan party', NULL, NULL, 0, TRUE, NULL, NULL, NULL, NULL);
INSERT INTO party VALUES ('akhil bharatiya hind kranti party', NULL, NULL, 0, TRUE, NULL, NULL, NULL, NULL);
INSERT INTO party VALUES ('akhil bharat hindu mahasabha', NULL, NULL, 0, TRUE, NULL, NULL, NULL, NULL);
INSERT INTO party VALUES ('akhil bharatiya sena', NULL, NULL, 0, TRUE, NULL, NULL, NULL, NULL);
INSERT INTO party VALUES ('akhil bharatiya janata congress', NULL, NULL, 0, TRUE, NULL, NULL, NULL, NULL);
INSERT INTO party VALUES ('all india bharti jug party', NULL, NULL, 0, TRUE, NULL, NULL, NULL, NULL);
INSERT INTO party VALUES ('akhil bharatiya jan sangh', NULL, NULL, 0, TRUE, NULL, NULL, NULL, NULL);
INSERT INTO party VALUES ('akhil bhartiya janata vikas party', NULL, NULL, 0, TRUE, NULL, NULL, NULL, NULL);
INSERT INTO party VALUES ('akhil bharatiya kisan mazdoor morcha', NULL, NULL, 0, TRUE, NULL, NULL, NULL, NULL);
INSERT INTO party VALUES ('akhil bharatiya lok tantrik alp-sankhyak jan morcha', NULL, NULL, 0, TRUE, NULL, NULL, NULL, NULL);
INSERT INTO party VALUES ('akhil bhartiya lok tantrik congress', NULL, NULL, 0, TRUE, NULL, NULL, NULL, NULL);
INSERT INTO party VALUES ('akhil bharatiya loktantra party', NULL, NULL, 0, TRUE, NULL, NULL, NULL, NULL);
INSERT INTO party VALUES ('akhil bharatiya manav adhikar dal', NULL, NULL, 0, TRUE, NULL, NULL, NULL, NULL);
INSERT INTO party VALUES ('akhil bhartiya manavata paksha', NULL, NULL, 0, TRUE, NULL, NULL, NULL, NULL);
INSERT INTO party VALUES ('akhil bharatiya manav seva dal', NULL, NULL, 0, TRUE, NULL, NULL, NULL, NULL);
INSERT INTO party VALUES ('akahand bharat maha sangh sarvahara krantikari party', NULL, NULL, 0, TRUE, NULL, NULL, NULL, NULL);
INSERT INTO party VALUES ('ambedkarbadi party', NULL, NULL, 0, TRUE, NULL, NULL, NULL, NULL);
INSERT INTO party VALUES ('akhil bharatiya rashtriya azad hind party', NULL, NULL, 0, TRUE, NULL, NULL, NULL, NULL);
INSERT INTO party VALUES ('akhil bharatiya rajivwadi congress (dubey)', NULL, NULL, 0, TRUE, NULL, NULL, NULL, NULL);
INSERT INTO party VALUES ('akhil bharatiya ram rajya parishad (prem ballabh vy', NULL, NULL, 0, TRUE, NULL, NULL, NULL, NULL);
INSERT INTO party VALUES ('akhil bharatiya rajarya sabha', NULL, NULL, 0, TRUE, NULL, NULL, NULL, NULL);
INSERT INTO party VALUES ('akhil bharatiya revolutionary shoshit samaj dal', NULL, NULL, 0, TRUE, NULL, NULL, NULL, NULL);
INSERT INTO party VALUES ('akhil bharatiya shivsena rashtrawadi', NULL, NULL, 0, TRUE, NULL, NULL, NULL, NULL);
INSERT INTO party VALUES ('akhil bhartiya sindhu samajwadi party', NULL, NULL, 0, TRUE, NULL, NULL, NULL, NULL);
INSERT INTO party VALUES ('arunachal congress', NULL, NULL, 0, TRUE, NULL, NULL, NULL, NULL);
INSERT INTO party VALUES ('a-chik national congress(democratic)', NULL, NULL, 0, TRUE, NULL, NULL, NULL, NULL);
INSERT INTO party VALUES ('apna dal', NULL, NULL, 0, TRUE, NULL, NULL, NULL, NULL);
INSERT INTO party VALUES ('all india anna dravida munnetra kazhagam', NULL, NULL, 0, TRUE, NULL, NULL, NULL, NULL);
INSERT INTO party VALUES ('anaithindia dravidar samudaya munnetra kazhagam', NULL, NULL, 0, TRUE, NULL, NULL, NULL, NULL);
INSERT INTO party VALUES ('aadivasi sena party', NULL, NULL, 0, TRUE, NULL, NULL, NULL, NULL);
INSERT INTO party VALUES ('asom gana parishad', NULL, NULL, 0, TRUE, NULL, NULL, NULL, NULL);
INSERT INTO party VALUES ('agrajan party', NULL, NULL, 0, TRUE, NULL, NULL, NULL, NULL);
INSERT INTO party VALUES ('all india bahujan samman party', NULL, NULL, 0, TRUE, NULL, NULL, NULL, NULL);
INSERT INTO party VALUES ('advait ishwasyam congress', NULL, NULL, 0, TRUE, NULL, NULL, NULL, NULL);
INSERT INTO party VALUES ('all india dalit welfare congress', NULL, NULL, 0, TRUE, NULL, NULL, NULL, NULL);
INSERT INTO party VALUES ('all india forward bloc (subhasist)', NULL, NULL, 0, TRUE, NULL, NULL, NULL, NULL);
INSERT INTO party VALUES ('all india gareeb congress', NULL, NULL, 0, TRUE, NULL, NULL, NULL, NULL);
INSERT INTO party VALUES ('all india indira congress (secular)', NULL, NULL, 0, TRUE, NULL, NULL, NULL, NULL);
INSERT INTO party VALUES ('akhila india jananayaka makkal katchi (dr. issac)', NULL, NULL, 0, TRUE, NULL, NULL, NULL, NULL);
INSERT INTO party VALUES ('all india minorities front', NULL, NULL, 0, TRUE, NULL, NULL, NULL, NULL);
INSERT INTO party VALUES ('all india majlis-e-ittehadul muslimeen', NULL, NULL, 0, TRUE, NULL, NULL, NULL, NULL);
INSERT INTO party VALUES ('all india muslim forum', NULL, NULL, 0, TRUE, NULL, NULL, NULL, NULL);
INSERT INTO party VALUES ('all india rashtriya janata party', NULL, NULL, 0, TRUE, NULL, NULL, NULL, NULL);
INSERT INTO party VALUES ('all india rajiv krantikari congress', NULL, NULL, 0, TRUE, NULL, NULL, NULL, NULL);
INSERT INTO party VALUES ('all india raksha party', NULL, NULL, 0, TRUE, NULL, NULL, NULL, NULL);
INSERT INTO party VALUES ('all india trinamool congress', NULL, NULL, 0, TRUE, NULL, NULL, NULL, NULL);
INSERT INTO party VALUES ('akila india vallalar peravai', NULL, NULL, 0, TRUE, NULL, NULL, NULL, NULL);
INSERT INTO party VALUES ('ajeya bharat party', NULL, NULL, 0, TRUE, NULL, NULL, NULL, NULL);
INSERT INTO party VALUES ('all j & k peoples patriotic front', NULL, NULL, 0, TRUE, NULL, NULL, NULL, NULL);
INSERT INTO party VALUES ('alpjan samaj party', NULL, NULL, 0, TRUE, NULL, NULL, NULL, NULL);
INSERT INTO party VALUES ('all jharkhand students union', NULL, NULL, 0, TRUE, NULL, NULL, NULL, NULL);
INSERT INTO party VALUES ('ajsu party', NULL, NULL, 0, TRUE, NULL, NULL, NULL, NULL);
INSERT INTO party VALUES ('all kerala m.g.rdravida munnetra party', NULL, NULL, 0, TRUE, NULL, NULL, NULL, NULL);
INSERT INTO party VALUES ('adarash lok dal', NULL, NULL, 0, TRUE, NULL, NULL, NULL, NULL);
INSERT INTO party VALUES ('amra bangalee', NULL, NULL, 0, TRUE, NULL, NULL, NULL, NULL);
INSERT INTO party VALUES ('ambedkar national congress', NULL, NULL, 0, TRUE, NULL, NULL, NULL, NULL);
INSERT INTO party VALUES ('andhra nadu party', NULL, NULL, 0, TRUE, NULL, NULL, NULL, NULL);
INSERT INTO party VALUES ('awami party', NULL, NULL, 0, TRUE, NULL, NULL, NULL, NULL);
INSERT INTO party VALUES ('ambedkar pragatisheel republican dal', NULL, NULL, 0, TRUE, NULL, NULL, NULL, NULL);
INSERT INTO party VALUES ('ambedkarist republican party', NULL, NULL, 0, TRUE, NULL, NULL, NULL, NULL);
INSERT INTO party VALUES ('akhil rashtrawadi party', NULL, NULL, 0, TRUE, NULL, NULL, NULL, NULL);
INSERT INTO party VALUES ('autonomous state demand committee', NULL, NULL, 0, TRUE, NULL, NULL, NULL, NULL);
INSERT INTO party VALUES ('ambedkar samaj party', NULL, NULL, 0, TRUE, NULL, NULL, NULL, NULL);
INSERT INTO party VALUES ('anna telugu desam party', NULL, NULL, 0, TRUE, NULL, NULL, NULL, NULL);
INSERT INTO party VALUES ('assam united democratic front', NULL, NULL, 0, TRUE, NULL, NULL, NULL, NULL);
INSERT INTO party VALUES ('adarshwadi dal', NULL, NULL, 0, TRUE, NULL, NULL, NULL, NULL);
INSERT INTO party VALUES ('bharatiya asht jan party', NULL, NULL, 0, TRUE, NULL, NULL, NULL, NULL);
INSERT INTO party VALUES ('bundelkhand akikrit party', NULL, NULL, 0, TRUE, NULL, NULL, NULL, NULL);
INSERT INTO party VALUES ('bharipa bahujan mahasangha', NULL, NULL, 0, TRUE, NULL, NULL, NULL, NULL);
INSERT INTO party VALUES ('bharatiya berozgar mazdoor kisan dal', NULL, NULL, 0, TRUE, NULL, NULL, NULL, NULL);
INSERT INTO party VALUES ('bharatiya backward party', NULL, NULL, 0, TRUE, NULL, NULL, NULL, NULL);
INSERT INTO party VALUES ('backward classes democratic party', NULL, NULL, 0, TRUE, NULL, NULL, NULL, NULL);
INSERT INTO party VALUES ('bhartiya chaitanya party', NULL, NULL, 0, TRUE, NULL, NULL, NULL, NULL);
INSERT INTO party VALUES ('b. c. united front', NULL, NULL, 0, TRUE, NULL, NULL, NULL, NULL);
INSERT INTO party VALUES ('bhrishtachar virodhi dal', NULL, NULL, 0, TRUE, NULL, NULL, NULL, NULL);
INSERT INTO party VALUES ('bharat dal', NULL, NULL, 0, TRUE, NULL, NULL, NULL, NULL);
INSERT INTO party VALUES ('bhartiya deshbhakt party', NULL, NULL, 0, TRUE, NULL, NULL, NULL, NULL);
INSERT INTO party VALUES ('bharatiya ekta dal', NULL, NULL, 0, TRUE, NULL, NULL, NULL, NULL);
INSERT INTO party VALUES ('bharatiya eklavya party', NULL, NULL, 0, TRUE, NULL, NULL, NULL, NULL);
INSERT INTO party VALUES ('bahujan ekta party (r)', NULL, NULL, 0, TRUE, NULL, NULL, NULL, NULL);
INSERT INTO party VALUES ('bharatiya grameen dal', NULL, NULL, 0, TRUE, NULL, NULL, NULL, NULL);
INSERT INTO party VALUES ('bharatiya gaon taj dal', NULL, NULL, 0, TRUE, NULL, NULL, NULL, NULL);
INSERT INTO party VALUES ('bharatiya bahujan party', NULL, NULL, 0, TRUE, NULL, NULL, NULL, NULL);
INSERT INTO party VALUES ('bhartiya congress (m)', NULL, NULL, 0, TRUE, NULL, NULL, NULL, NULL);
INSERT INTO party VALUES ('bhartiya jagran party', NULL, NULL, 0, TRUE, NULL, NULL, NULL, NULL);
INSERT INTO party VALUES ('bharatiya jan congress', NULL, NULL, 0, TRUE, NULL, NULL, NULL, NULL);
INSERT INTO party VALUES ('bharatiya jan vikas party', NULL, NULL, 0, TRUE, NULL, NULL, NULL, NULL);
INSERT INTO party VALUES ('bharatiya pichhra dal', NULL, NULL, 0, TRUE, NULL, NULL, NULL, NULL);
INSERT INTO party VALUES ('bharatiya peoples party', NULL, NULL, 0, TRUE, NULL, NULL, NULL, NULL);
INSERT INTO party VALUES ('bharatheeya sadharma samsthapana party', NULL, NULL, 0, TRUE, NULL, NULL, NULL, NULL);
INSERT INTO party VALUES ('bharatiya jan berojgar chhatra dal', NULL, NULL, 0, TRUE, NULL, NULL, NULL, NULL);
INSERT INTO party VALUES ('bharatiya jai bheem party', NULL, NULL, 0, TRUE, NULL, NULL, NULL, NULL);
INSERT INTO party VALUES ('bihar jana congress', NULL, NULL, 0, TRUE, NULL, NULL, NULL, NULL);
INSERT INTO party VALUES ('bhartiya jana congress (rashtriya)', NULL, NULL, 0, TRUE, NULL, NULL, NULL, NULL);
INSERT INTO party VALUES ('biju janata dal', NULL, NULL, 0, TRUE, NULL, NULL, NULL, NULL);
INSERT INTO party VALUES ('bharatiya jantantrik janta dal', NULL, NULL, 0, TRUE, NULL, NULL, NULL, NULL);
INSERT INTO party VALUES ('bharatiya jan jagruti party', NULL, NULL, 0, TRUE, NULL, NULL, NULL, NULL);
INSERT INTO party VALUES ('bharatiya jan kranti dal (democratic)', NULL, NULL, 0, TRUE, NULL, NULL, NULL, NULL);
INSERT INTO party VALUES ('bajjikanchal vikas party', NULL, NULL, 0, TRUE, NULL, NULL, NULL, NULL);
INSERT INTO party VALUES ('bharatiya janata party', NULL, NULL, 0, TRUE, NULL, NULL, NULL, NULL);
INSERT INTO party VALUES ('bhartiya jan sabha', NULL, NULL, 0, TRUE, NULL, NULL, NULL, NULL);
INSERT INTO party VALUES ('bharatiya jan shakti', NULL, NULL, 0, TRUE, NULL, NULL, NULL, NULL);
INSERT INTO party VALUES ('bharatiya jantantrik parishad', NULL, NULL, 0, TRUE, NULL, NULL, NULL, NULL);
INSERT INTO party VALUES ('bharatiya janvadi party', NULL, NULL, 0, TRUE, NULL, NULL, NULL, NULL);
INSERT INTO party VALUES ('bahujan kisan dal', NULL, NULL, 0, TRUE, NULL, NULL, NULL, NULL);
INSERT INTO party VALUES ('bahujan kranti dal (jai)', NULL, NULL, 0, TRUE, NULL, NULL, NULL, NULL);
INSERT INTO party VALUES ('bharatiya kisan kamgar party', NULL, NULL, 0, TRUE, NULL, NULL, NULL, NULL);
INSERT INTO party VALUES ('bharatiya krantikari kammand party', NULL, NULL, 0, TRUE, NULL, NULL, NULL, NULL);
INSERT INTO party VALUES ('bharat ki lok jimmedar party', NULL, NULL, 0, TRUE, NULL, NULL, NULL, NULL);
INSERT INTO party VALUES ('bharat kranti rakshak party', NULL, NULL, 0, TRUE, NULL, NULL, NULL, NULL);
INSERT INTO party VALUES ('bharatiya lok kalyan dal', NULL, NULL, 0, TRUE, NULL, NULL, NULL, NULL);
INSERT INTO party VALUES ('bharti lok lehar party', NULL, NULL, 0, TRUE, NULL, NULL, NULL, NULL);
INSERT INTO party VALUES ('bharatiya labour party', NULL, NULL, 0, TRUE, NULL, NULL, NULL, NULL);
INSERT INTO party VALUES ('bharatiya loktantrik party(gandhi-lohiawadi)', NULL, NULL, 0, TRUE, NULL, NULL, NULL, NULL);
INSERT INTO party VALUES ('bharatha makkal congress', NULL, NULL, 0, TRUE, NULL, NULL, NULL, NULL);
INSERT INTO party VALUES ('bharatiya momin front', NULL, NULL, 0, TRUE, NULL, NULL, NULL, NULL);
INSERT INTO party VALUES ('bundelkhand mukti morcha', NULL, NULL, 0, TRUE, NULL, NULL, NULL, NULL);
INSERT INTO party VALUES ('bharatiya muhabbat party (all india)', NULL, NULL, 0, TRUE, NULL, NULL, NULL, NULL);
INSERT INTO party VALUES ('bharatiya minorities suraksha mahasangh', NULL, NULL, 0, TRUE, NULL, NULL, NULL, NULL);
INSERT INTO party VALUES ('bharatiya manavata vikas party', NULL, NULL, 0, TRUE, NULL, NULL, NULL, NULL);
INSERT INTO party VALUES ('bharatiya naujawan dal', NULL, NULL, 0, TRUE, NULL, NULL, NULL, NULL);
INSERT INTO party VALUES ('bharatiya natiional janta dal', NULL, NULL, 0, TRUE, NULL, NULL, NULL, NULL);
INSERT INTO party VALUES ('bharat nav jyoti sangh', NULL, NULL, 0, TRUE, NULL, NULL, NULL, NULL);
INSERT INTO party VALUES ('bharatiya navshakti party', NULL, NULL, 0, TRUE, NULL, NULL, NULL, NULL);
INSERT INTO party VALUES ('bharatiya nagrik party', NULL, NULL, 0, TRUE, NULL, NULL, NULL, NULL);
INSERT INTO party VALUES ('bira oriya party', NULL, NULL, 0, TRUE, NULL, NULL, NULL, NULL);
INSERT INTO party VALUES ('bodaland peoples front', NULL, NULL, 0, TRUE, NULL, NULL, NULL, NULL);
INSERT INTO party VALUES ('bhartiya pragatisheel congress', NULL, NULL, 0, TRUE, NULL, NULL, NULL, NULL);
INSERT INTO party VALUES ('bharat punarnirman dal', NULL, NULL, 0, TRUE, NULL, NULL, NULL, NULL);
INSERT INTO party VALUES ('bharatiya praja paksha', NULL, NULL, 0, TRUE, NULL, NULL, NULL, NULL);
INSERT INTO party VALUES ('bharatiya parivartan morcha', NULL, NULL, 0, TRUE, NULL, NULL, NULL, NULL);
INSERT INTO party VALUES ('bharatiya prajatantrik shudh gandhiwadi krishak dal', NULL, NULL, 0, TRUE, NULL, NULL, NULL, NULL);
INSERT INTO party VALUES ('bihar people???s party', NULL, NULL, 0, TRUE, NULL, NULL, NULL, NULL);
INSERT INTO party VALUES ('bharatiya prajatantra party', NULL, NULL, 0, TRUE, NULL, NULL, NULL, NULL);
INSERT INTO party VALUES ('bharatiya rajiv congress', NULL, NULL, 0, TRUE, NULL, NULL, NULL, NULL);
INSERT INTO party VALUES ('bahujan republican ekta manch', NULL, NULL, 0, TRUE, NULL, NULL, NULL, NULL);
INSERT INTO party VALUES ('bharatiya rashtriya morcha', NULL, NULL, 0, TRUE, NULL, NULL, NULL, NULL);
INSERT INTO party VALUES ('bharatiya rashtravadi paksha', NULL, NULL, 0, TRUE, NULL, NULL, NULL, NULL);
INSERT INTO party VALUES ('bharatiya republican paksha', NULL, NULL, 0, TRUE, NULL, NULL, NULL, NULL);
INSERT INTO party VALUES ('bharatiya vikash party', NULL, NULL, 0, TRUE, NULL, NULL, NULL, NULL);
INSERT INTO party VALUES ('bahujan shakty', NULL, NULL, 0, TRUE, NULL, NULL, NULL, NULL);
INSERT INTO party VALUES ('bharathiya sahayog congress', NULL, NULL, 0, TRUE, NULL, NULL, NULL, NULL);
INSERT INTO party VALUES ('bharatiya samaj dal', NULL, NULL, 0, TRUE, NULL, NULL, NULL, NULL);
INSERT INTO party VALUES ('bharti sarvadarshi parishad', NULL, NULL, 0, TRUE, NULL, NULL, NULL, NULL);
INSERT INTO party VALUES ('bharatiya surajya manch', NULL, NULL, 0, TRUE, NULL, NULL, NULL, NULL);
INSERT INTO party VALUES ('bharatiya sarvkalayan kranti dal', NULL, NULL, 0, TRUE, NULL, NULL, NULL, NULL);
INSERT INTO party VALUES ('bharatiya sarvodaya kranti party', NULL, NULL, 0, TRUE, NULL, NULL, NULL, NULL);
INSERT INTO party VALUES ('bharatiya samaj kalyan party bharat', NULL, NULL, 0, TRUE, NULL, NULL, NULL, NULL);
INSERT INTO party VALUES ('bharatiya sampuran krantikari party', NULL, NULL, 0, TRUE, NULL, NULL, NULL, NULL);
INSERT INTO party VALUES ('bahujan samaj party', NULL, NULL, 0, TRUE, NULL, NULL, NULL, NULL);
INSERT INTO party VALUES ('bahujan samaj party (ambedkar)', NULL, NULL, 0, TRUE, NULL, NULL, NULL, NULL);
INSERT INTO party VALUES ('bahujan samaj party(ambedkar-phule)', NULL, NULL, 0, TRUE, NULL, NULL, NULL, NULL);
INSERT INTO party VALUES ('bahujan sangharsh party (kanshiram)', NULL, NULL, 0, TRUE, NULL, NULL, NULL, NULL);
INSERT INTO party VALUES ('bharatiya subhash sena', NULL, NULL, 0, TRUE, NULL, NULL, NULL, NULL);
INSERT INTO party VALUES ('bharatiya sadbhawna samaj party', NULL, NULL, 0, TRUE, NULL, NULL, NULL, NULL);
INSERT INTO party VALUES ('bharatiya samta samaj party', NULL, NULL, 0, TRUE, NULL, NULL, NULL, NULL);
INSERT INTO party VALUES ('bharat uday mission', NULL, NULL, 0, TRUE, NULL, NULL, NULL, NULL);
INSERT INTO party VALUES ('bahujan uday manch', NULL, NULL, 0, TRUE, NULL, NULL, NULL, NULL);
INSERT INTO party VALUES ('bahujan vikas aaghadi', NULL, NULL, 0, TRUE, NULL, NULL, NULL, NULL);
INSERT INTO party VALUES ('bharat vikas morcha', NULL, NULL, 0, TRUE, NULL, NULL, NULL, NULL);
INSERT INTO party VALUES ('bahujan vikas party', NULL, NULL, 0, TRUE, NULL, NULL, NULL, NULL);
INSERT INTO party VALUES ('buddhiviveki vikas party', NULL, NULL, 0, TRUE, NULL, NULL, NULL, NULL);
INSERT INTO party VALUES ('christian democratic front', NULL, NULL, 0, TRUE, NULL, NULL, NULL, NULL);
INSERT INTO party VALUES ('chhattisgarh vikas party', NULL, NULL, 0, TRUE, NULL, NULL, NULL, NULL);
INSERT INTO party VALUES ('christian mannetra kazhagam', NULL, NULL, 0, TRUE, NULL, NULL, NULL, NULL);
INSERT INTO party VALUES ('chhattisgarh mukti morcha', NULL, NULL, 0, TRUE, NULL, NULL, NULL, NULL);
INSERT INTO party VALUES ('communist party of india', NULL, NULL, 0, TRUE, NULL, NULL, NULL, NULL);
INSERT INTO party VALUES ('communist party of india (marxist-leninist) (liberation)', NULL, NULL, 0, TRUE, NULL, NULL, NULL, NULL);
INSERT INTO party VALUES ('communist party of india (marxist)', NULL, NULL, 0, TRUE, NULL, NULL, NULL, NULL);
INSERT INTO party VALUES ('chhattisgarhi samaj party', NULL, NULL, 0, TRUE, NULL, NULL, NULL, NULL);
INSERT INTO party VALUES ('champaran vikas party', NULL, NULL, 0, TRUE, NULL, NULL, NULL, NULL);
INSERT INTO party VALUES ('desh bhakt party', NULL, NULL, 0, TRUE, NULL, NULL, NULL, NULL);
INSERT INTO party VALUES ('democratic bahujan samaj morcha', NULL, NULL, 0, TRUE, NULL, NULL, NULL, NULL);
INSERT INTO party VALUES ('democratic bharatiya samaj party', NULL, NULL, 0, TRUE, NULL, NULL, NULL, NULL);
INSERT INTO party VALUES ('democratic congress party', NULL, NULL, 0, TRUE, NULL, NULL, NULL, NULL);
INSERT INTO party VALUES ('democratic secular party', NULL, NULL, 0, TRUE, NULL, NULL, NULL, NULL);
INSERT INTO party VALUES ('duggar pradesh party', NULL, NULL, 0, TRUE, NULL, NULL, NULL, NULL);
INSERT INTO party VALUES ('desiya murpokku dravida kazhagam', NULL, NULL, 0, TRUE, NULL, NULL, NULL, NULL);
INSERT INTO party VALUES ('dravida munnetra kazhagam', NULL, NULL, 0, TRUE, NULL, NULL, NULL, NULL);
INSERT INTO party VALUES ('democratic party of india', NULL, NULL, 0, TRUE, NULL, NULL, NULL, NULL);
INSERT INTO party VALUES ('desia pathukappu kazhagam', NULL, NULL, 0, TRUE, NULL, NULL, NULL, NULL);
INSERT INTO party VALUES ('dhiravida thelgar munnetra kalagam', NULL, NULL, 0, TRUE, NULL, NULL, NULL, NULL);
INSERT INTO party VALUES ('ekta kranti dal u.p.', NULL, NULL, 0, TRUE, NULL, NULL, NULL, NULL);
INSERT INTO party VALUES ('eklavya samaj party', NULL, NULL, 0, TRUE, NULL, NULL, NULL, NULL);
INSERT INTO party VALUES ('ekta shakti', NULL, NULL, 0, TRUE, NULL, NULL, NULL, NULL);
INSERT INTO party VALUES ('ephraim union', NULL, NULL, 0, TRUE, NULL, NULL, NULL, NULL);
INSERT INTO party VALUES ('forward bloc (socialist)', NULL, NULL, 0, TRUE, NULL, NULL, NULL, NULL);
INSERT INTO party VALUES ('all india forward bloc', NULL, NULL, 0, TRUE, NULL, NULL, NULL, NULL);
INSERT INTO party VALUES ('federal congress of india', NULL, NULL, 0, TRUE, NULL, NULL, NULL, NULL);
INSERT INTO party VALUES ('federal party of manipur', NULL, NULL, 0, TRUE, NULL, NULL, NULL, NULL);
INSERT INTO party VALUES ('gondvana gantantra party', NULL, NULL, 0, TRUE, NULL, NULL, NULL, NULL);
INSERT INTO party VALUES ('golden india party', NULL, NULL, 0, TRUE, NULL, NULL, NULL, NULL);
INSERT INTO party VALUES ('gondwana mukti sena', NULL, NULL, 0, TRUE, NULL, NULL, NULL, NULL);
INSERT INTO party VALUES ('garo national council', NULL, NULL, 0, TRUE, NULL, NULL, NULL, NULL);
INSERT INTO party VALUES ('gandhiwadi rashtriya congress', NULL, NULL, 0, TRUE, NULL, NULL, NULL, NULL);
INSERT INTO party VALUES ('great india party', NULL, NULL, 0, TRUE, NULL, NULL, NULL, NULL);
INSERT INTO party VALUES ('gareebjan samaj party', NULL, NULL, 0, TRUE, NULL, NULL, NULL, NULL);
INSERT INTO party VALUES ('goa vikas party', NULL, NULL, 0, TRUE, NULL, NULL, NULL, NULL);
INSERT INTO party VALUES ('gujarat yuva vikas party', NULL, NULL, 0, TRUE, NULL, NULL, NULL, NULL);
INSERT INTO party VALUES ('hind vikas party', NULL, NULL, 0, TRUE, NULL, NULL, NULL, NULL);
INSERT INTO party VALUES ('hindu ekta andolan party', NULL, NULL, 0, TRUE, NULL, NULL, NULL, NULL);
INSERT INTO party VALUES ('hindustan inqualab party', NULL, NULL, 0, TRUE, NULL, NULL, NULL, NULL);
INSERT INTO party VALUES ('haryana janhit congress (bl)', NULL, NULL, 0, TRUE, NULL, NULL, NULL, NULL);
INSERT INTO party VALUES ('hindustan janta party', NULL, NULL, 0, TRUE, NULL, NULL, NULL, NULL);
INSERT INTO party VALUES ('hind kisan mazdoor party', NULL, NULL, 0, TRUE, NULL, NULL, NULL, NULL);
INSERT INTO party VALUES ('haryana lok dal (rastriya)', NULL, NULL, 0, TRUE, NULL, NULL, NULL, NULL);
INSERT INTO party VALUES ('hind morcha', NULL, NULL, 0, TRUE, NULL, NULL, NULL, NULL);
INSERT INTO party VALUES ('hill state people''s democratic party', NULL, NULL, 0, TRUE, NULL, NULL, NULL, NULL);
INSERT INTO party VALUES ('himachal vikas congress', NULL, NULL, 0, TRUE, NULL, NULL, NULL, NULL);
INSERT INTO party VALUES ('haryana vikas party', NULL, NULL, 0, TRUE, NULL, NULL, NULL, NULL);
INSERT INTO party VALUES ('indian bahujan samajwadi party', NULL, NULL, 0, TRUE, NULL, NULL, NULL, NULL);
INSERT INTO party VALUES ('indian congress (socialist)', NULL, NULL, 0, TRUE, NULL, NULL, NULL, NULL);
INSERT INTO party VALUES ('indian christian secular party', NULL, NULL, 0, TRUE, NULL, NULL, NULL, NULL);
INSERT INTO party VALUES ('indian federal democratic party', NULL, NULL, 0, TRUE, NULL, NULL, NULL, NULL);
INSERT INTO party VALUES ('indian justice party', NULL, NULL, 0, TRUE, NULL, NULL, NULL, NULL);
INSERT INTO party VALUES ('indian national congress', NULL, NULL, 0, TRUE, NULL, NULL, NULL, NULL);
INSERT INTO party VALUES ('indian national green party', NULL, NULL, 0, TRUE, NULL, NULL, NULL, NULL);
INSERT INTO party VALUES ('indian national league', NULL, NULL, 0, TRUE, NULL, NULL, NULL, NULL);
INSERT INTO party VALUES ('indian national lok dal', NULL, NULL, 0, TRUE, NULL, NULL, NULL, NULL);
INSERT INTO party VALUES ('indian people''s forward block', NULL, NULL, 0, TRUE, NULL, NULL, NULL, NULL);
INSERT INTO party VALUES ('indian peace party', NULL, NULL, 0, TRUE, NULL, NULL, NULL, NULL);
INSERT INTO party VALUES ('indian republican front', NULL, NULL, 0, TRUE, NULL, NULL, NULL, NULL);
INSERT INTO party VALUES ('indian union muslim league', NULL, NULL, 0, TRUE, NULL, NULL, NULL, NULL);
INSERT INTO party VALUES ('inqalab vikas dal', NULL, NULL, 0, TRUE, NULL, NULL, NULL, NULL);
INSERT INTO party VALUES ('jaganmay nari sangathan', NULL, NULL, 0, TRUE, NULL, NULL, NULL, NULL);
INSERT INTO party VALUES ('jai bharat party', NULL, NULL, 0, TRUE, NULL, NULL, NULL, NULL);
INSERT INTO party VALUES ('jai bharat samanta party', NULL, NULL, 0, TRUE, NULL, NULL, NULL, NULL);
INSERT INTO party VALUES ('jai chhattisgarh party', NULL, NULL, 0, TRUE, NULL, NULL, NULL, NULL);
INSERT INTO party VALUES ('jan chetna party', NULL, NULL, 0, TRUE, NULL, NULL, NULL, NULL);
INSERT INTO party VALUES ('janata dal', NULL, NULL, 0, TRUE, NULL, NULL, NULL, NULL);
INSERT INTO party VALUES ('janata dal (secular)', NULL, NULL, 0, TRUE, NULL, NULL, NULL, NULL);
INSERT INTO party VALUES ('janata dal (united)', NULL, NULL, 0, TRUE, NULL, NULL, NULL, NULL);
INSERT INTO party VALUES ('jharkhand disom party', NULL, NULL, 0, TRUE, NULL, NULL, NULL, NULL);
INSERT INTO party VALUES ('jago party', NULL, NULL, 0, TRUE, NULL, NULL, NULL, NULL);
INSERT INTO party VALUES ('jharkhand janadikhar manch', NULL, NULL, 0, TRUE, NULL, NULL, NULL, NULL);
INSERT INTO party VALUES ('jharkhand jan morcha', NULL, NULL, 0, TRUE, NULL, NULL, NULL, NULL);
INSERT INTO party VALUES ('jana hitkari party', NULL, NULL, 0, TRUE, NULL, NULL, NULL, NULL);
INSERT INTO party VALUES ('jai hind party', NULL, NULL, 0, TRUE, NULL, NULL, NULL, NULL);
INSERT INTO party VALUES ('janhit samaj party', NULL, NULL, 0, TRUE, NULL, NULL, NULL, NULL);
INSERT INTO party VALUES ('jebamani janata', NULL, NULL, 0, TRUE, NULL, NULL, NULL, NULL);
INSERT INTO party VALUES ('jai jawan jai kisan mazdoor congress', NULL, NULL, 0, TRUE, NULL, NULL, NULL, NULL);
INSERT INTO party VALUES ('jammu and kashmir awami league', NULL, NULL, 0, TRUE, NULL, NULL, NULL, NULL);
INSERT INTO party VALUES ('jammu & kashmir awami national conference', NULL, NULL, 0, TRUE, NULL, NULL, NULL, NULL);
INSERT INTO party VALUES ('jan ekta dal', NULL, NULL, 0, TRUE, NULL, NULL, NULL, NULL);
INSERT INTO party VALUES ('jawan kisan morcha', NULL, NULL, 0, TRUE, NULL, NULL, NULL, NULL);
INSERT INTO party VALUES ('jammu & kashmir national conference', NULL, NULL, 0, TRUE, NULL, NULL, NULL, NULL);
INSERT INTO party VALUES ('jammu & kashmir national panthers party', NULL, NULL, 0, TRUE, NULL, NULL, NULL, NULL);
INSERT INTO party VALUES ('jharkhand party', NULL, NULL, 0, TRUE, NULL, NULL, NULL, NULL);
INSERT INTO party VALUES ('jharkhand party (naren)', NULL, NULL, 0, TRUE, NULL, NULL, NULL, NULL);
INSERT INTO party VALUES ('jammu & kashmir peoples democratic party', NULL, NULL, 0, TRUE, NULL, NULL, NULL, NULL);
INSERT INTO party VALUES ('jharkhand people''s party', NULL, NULL, 0, TRUE, NULL, NULL, NULL, NULL);
INSERT INTO party VALUES ('jan morcha', NULL, NULL, 0, TRUE, NULL, NULL, NULL, NULL);
INSERT INTO party VALUES ('jharkhand mukti morcha', NULL, NULL, 0, TRUE, NULL, NULL, NULL, NULL);
INSERT INTO party VALUES ('jharkhand mukti morcha (mardi)', NULL, NULL, 0, TRUE, NULL, NULL, NULL, NULL);
INSERT INTO party VALUES ('jharkhand mukti morcha (ulgulan)', NULL, NULL, 0, TRUE, NULL, NULL, NULL, NULL);
INSERT INTO party VALUES ('janmangal paksh', NULL, NULL, 0, TRUE, NULL, NULL, NULL, NULL);
INSERT INTO party VALUES ('janata party', NULL, NULL, 0, TRUE, NULL, NULL, NULL, NULL);
INSERT INTO party VALUES ('jammu & kashmir people conference', NULL, NULL, 0, TRUE, NULL, NULL, NULL, NULL);
INSERT INTO party VALUES ('janvadi party(socialist)', NULL, NULL, 0, TRUE, NULL, NULL, NULL, NULL);
INSERT INTO party VALUES ('jan satta party', NULL, NULL, 0, TRUE, NULL, NULL, NULL, NULL);
INSERT INTO party VALUES ('jan samanta party', NULL, NULL, 0, TRUE, NULL, NULL, NULL, NULL);
INSERT INTO party VALUES ('jansatta party', NULL, NULL, 0, TRUE, NULL, NULL, NULL, NULL);
INSERT INTO party VALUES ('jan surajya shakti', NULL, NULL, 0, TRUE, NULL, NULL, NULL, NULL);
INSERT INTO party VALUES ('jai telengana party', NULL, NULL, 0, TRUE, NULL, NULL, NULL, NULL);
INSERT INTO party VALUES ('jana unnayan mancha', NULL, NULL, 0, TRUE, NULL, NULL, NULL, NULL);
INSERT INTO party VALUES ('janata uday party', NULL, NULL, 0, TRUE, NULL, NULL, NULL, NULL);
INSERT INTO party VALUES ('jharkhand vikas dal', NULL, NULL, 0, TRUE, NULL, NULL, NULL, NULL);
INSERT INTO party VALUES ('jharkhand vikas morcha (prajatantrik)', NULL, NULL, 0, TRUE, NULL, NULL, NULL, NULL);
INSERT INTO party VALUES ('janata vikas party', NULL, NULL, 0, TRUE, NULL, NULL, NULL, NULL);
INSERT INTO party VALUES ('kannada chalavali vatal paksha', NULL, NULL, 0, TRUE, NULL, NULL, NULL, NULL);
INSERT INTO party VALUES ('kamarajar deseeya congress', NULL, NULL, 0, TRUE, NULL, NULL, NULL, NULL);
INSERT INTO party VALUES ('kerala congress', NULL, NULL, 0, TRUE, NULL, NULL, NULL, NULL);
INSERT INTO party VALUES ('kerala congress (m)', NULL, NULL, 0, TRUE, NULL, NULL, NULL, NULL);
INSERT INTO party VALUES ('kranti kari jai hind sena', NULL, NULL, 0, TRUE, NULL, NULL, NULL, NULL);
INSERT INTO party VALUES ('krantisena maharashtra', NULL, NULL, 0, TRUE, NULL, NULL, NULL, NULL);
INSERT INTO party VALUES ('krantikari manuwadi morcha', NULL, NULL, 0, TRUE, NULL, NULL, NULL, NULL);
INSERT INTO party VALUES ('kannada nadu party', NULL, NULL, 0, TRUE, NULL, NULL, NULL, NULL);
INSERT INTO party VALUES ('kongu nadu munnetra kazhagam', NULL, NULL, 0, TRUE, NULL, NULL, NULL, NULL);
INSERT INTO party VALUES ('kosal kranti dal', NULL, NULL, 0, TRUE, NULL, NULL, NULL, NULL);
INSERT INTO party VALUES ('kranti dal', NULL, NULL, 0, TRUE, NULL, NULL, NULL, NULL);
INSERT INTO party VALUES ('karnataka rajya ryota sangha', NULL, NULL, 0, TRUE, NULL, NULL, NULL, NULL);
INSERT INTO party VALUES ('kalinga sena', NULL, NULL, 0, TRUE, NULL, NULL, NULL, NULL);
INSERT INTO party VALUES ('krantikari samyavadi party', NULL, NULL, 0, TRUE, NULL, NULL, NULL, NULL);
INSERT INTO party VALUES ('karnataka thamizhar munnetra kazhagam', NULL, NULL, 0, TRUE, NULL, NULL, NULL, NULL);
INSERT INTO party VALUES ('karnataka vikash party', NULL, NULL, 0, TRUE, NULL, NULL, NULL, NULL);
INSERT INTO party VALUES ('kisan vikas party', NULL, NULL, 0, TRUE, NULL, NULL, NULL, NULL);
INSERT INTO party VALUES ('kamjor varg sangh', NULL, NULL, 0, TRUE, NULL, NULL, NULL, NULL);
INSERT INTO party VALUES ('kosi vikas party', NULL, NULL, 0, TRUE, NULL, NULL, NULL, NULL);
INSERT INTO party VALUES ('lok bharati', NULL, NULL, 0, TRUE, NULL, NULL, NULL, NULL);
INSERT INTO party VALUES ('lok bhalai party', NULL, NULL, 0, TRUE, NULL, NULL, NULL, NULL);
INSERT INTO party VALUES ('loktantrik chetna party', NULL, NULL, 0, TRUE, NULL, NULL, NULL, NULL);
INSERT INTO party VALUES ('lok dal', NULL, NULL, 0, TRUE, NULL, NULL, NULL, NULL);
INSERT INTO party VALUES ('lok jan shakti party', NULL, NULL, 0, TRUE, NULL, NULL, NULL, NULL);
INSERT INTO party VALUES ('labour and job seeker''s party of india', NULL, NULL, 0, TRUE, NULL, NULL, NULL, NULL);
INSERT INTO party VALUES ('lok jan vikas morcha', NULL, NULL, 0, TRUE, NULL, NULL, NULL, NULL);
INSERT INTO party VALUES ('loktanrik janata party (secular)', NULL, NULL, 0, TRUE, NULL, NULL, NULL, NULL);
INSERT INTO party VALUES ('loksangram', NULL, NULL, 0, TRUE, NULL, NULL, NULL, NULL);
INSERT INTO party VALUES ('loktanrik sarkar party', NULL, NULL, 0, TRUE, NULL, NULL, NULL, NULL);
INSERT INTO party VALUES ('lal morcha', NULL, NULL, 0, TRUE, NULL, NULL, NULL, NULL);
INSERT INTO party VALUES ('labour party (secular)', NULL, NULL, 0, TRUE, NULL, NULL, NULL, NULL);
INSERT INTO party VALUES ('labour party of india(v.vprasad)', NULL, NULL, 0, TRUE, NULL, NULL, NULL, NULL);
INSERT INTO party VALUES ('lokpriya samaj party', NULL, NULL, 0, TRUE, NULL, NULL, NULL, NULL);
INSERT INTO party VALUES ('lok rajya party', NULL, NULL, 0, TRUE, NULL, NULL, NULL, NULL);
INSERT INTO party VALUES ('lok shakti', NULL, NULL, 0, TRUE, NULL, NULL, NULL, NULL);
INSERT INTO party VALUES ('lok sewa dal', NULL, NULL, 0, TRUE, NULL, NULL, NULL, NULL);
INSERT INTO party VALUES ('lok satta party', NULL, NULL, 0, TRUE, NULL, NULL, NULL, NULL);
INSERT INTO party VALUES ('laghujan samaj vikas party', NULL, NULL, 0, TRUE, NULL, NULL, NULL, NULL);
INSERT INTO party VALUES ('loktantrik samajwadi party', NULL, NULL, 0, TRUE, NULL, NULL, NULL, NULL);
INSERT INTO party VALUES ('loktantrik samata dal', NULL, NULL, 0, TRUE, NULL, NULL, NULL, NULL);
INSERT INTO party VALUES ('lok vikas party', NULL, NULL, 0, TRUE, NULL, NULL, NULL, NULL);
INSERT INTO party VALUES ('m.g.r.anna d.m.kazhagam', NULL, NULL, 0, TRUE, NULL, NULL, NULL, NULL);
INSERT INTO party VALUES ('moulik adhikar party', NULL, NULL, 0, TRUE, NULL, NULL, NULL, NULL);
INSERT INTO party VALUES ('maharashtrawadi gomantak', NULL, NULL, 0, TRUE, NULL, NULL, NULL, NULL);
INSERT INTO party VALUES ('manithaneya makkal katchi', NULL, NULL, 0, TRUE, NULL, NULL, NULL, NULL);
INSERT INTO party VALUES ('mana party', NULL, NULL, 0, TRUE, NULL, NULL, NULL, NULL);
INSERT INTO party VALUES ('mahila adhikar party', NULL, NULL, 0, TRUE, NULL, NULL, NULL, NULL);
INSERT INTO party VALUES ('mool bharati (s) party', NULL, NULL, 0, TRUE, NULL, NULL, NULL, NULL);
INSERT INTO party VALUES ('matra bhakta party', NULL, NULL, 0, TRUE, NULL, NULL, NULL, NULL);
INSERT INTO party VALUES ('majlis bachao tahreek', NULL, NULL, 0, TRUE, NULL, NULL, NULL, NULL);
INSERT INTO party VALUES ('momin conference', NULL, NULL, 0, TRUE, NULL, NULL, NULL, NULL);
INSERT INTO party VALUES ('marxist co-ordination', NULL, NULL, 0, TRUE, NULL, NULL, NULL, NULL);
INSERT INTO party VALUES ('marxist communist party of india (s.s. srivastava)', NULL, NULL, 0, TRUE, NULL, NULL, NULL, NULL);
INSERT INTO party VALUES ('mahan dal', NULL, NULL, 0, TRUE, NULL, NULL, NULL, NULL);
INSERT INTO party VALUES ('maraland democratic front', NULL, NULL, 0, TRUE, NULL, NULL, NULL, NULL);
INSERT INTO party VALUES ('marumalarchi dravida munnetra kazhagam', NULL, NULL, 0, TRUE, NULL, NULL, NULL, NULL);
INSERT INTO party VALUES ('meghalaya democratic party', NULL, NULL, 0, TRUE, NULL, NULL, NULL, NULL);
INSERT INTO party VALUES ('manav jagriti manch', NULL, NULL, 0, TRUE, NULL, NULL, NULL, NULL);
INSERT INTO party VALUES ('mahagujarat janta party', NULL, NULL, 0, TRUE, NULL, NULL, NULL, NULL);
INSERT INTO party VALUES ('maidani kranti dal', NULL, NULL, 0, TRUE, NULL, NULL, NULL, NULL);
INSERT INTO party VALUES ('manav kalyan sangh dal', NULL, NULL, 0, TRUE, NULL, NULL, NULL, NULL);
INSERT INTO party VALUES ('majdoor kisan union party', NULL, NULL, 0, TRUE, NULL, NULL, NULL, NULL);
INSERT INTO party VALUES ('makkal manadu katchi', NULL, NULL, 0, TRUE, NULL, NULL, NULL, NULL);
INSERT INTO party VALUES ('manav mukti morcha', NULL, NULL, 0, TRUE, NULL, NULL, NULL, NULL);
INSERT INTO party VALUES ('muslim majlis uttar pradesh', NULL, NULL, 0, TRUE, NULL, NULL, NULL, NULL);
INSERT INTO party VALUES ('mizo national front', NULL, NULL, 0, TRUE, NULL, NULL, NULL, NULL);
INSERT INTO party VALUES ('maharashtra navnirman sena', NULL, NULL, 0, TRUE, NULL, NULL, NULL, NULL);
INSERT INTO party VALUES ('manuvadi party', NULL, NULL, 0, TRUE, NULL, NULL, NULL, NULL);
INSERT INTO party VALUES ('moderate party', NULL, NULL, 0, TRUE, NULL, NULL, NULL, NULL);
INSERT INTO party VALUES ('manava party', NULL, NULL, 0, TRUE, NULL, NULL, NULL, NULL);
INSERT INTO party VALUES ('maharashtra pradesh krantikari party', NULL, NULL, 0, TRUE, NULL, NULL, NULL, NULL);
INSERT INTO party VALUES ('manipur peoples party', NULL, NULL, 0, TRUE, NULL, NULL, NULL, NULL);
INSERT INTO party VALUES ('maharashtra rashtravadi congress', NULL, NULL, 0, TRUE, NULL, NULL, NULL, NULL);
INSERT INTO party VALUES ('maharashtra rajiv congress', NULL, NULL, 0, TRUE, NULL, NULL, NULL, NULL);
INSERT INTO party VALUES ('mudiraj rashtriya samithi', NULL, NULL, 0, TRUE, NULL, NULL, NULL, NULL);
INSERT INTO party VALUES ('manipur state congress party', NULL, NULL, 0, TRUE, NULL, NULL, NULL, NULL);
INSERT INTO party VALUES ('manav samaj party', NULL, NULL, 0, TRUE, NULL, NULL, NULL, NULL);
INSERT INTO party VALUES ('muslim league kerala state committee', NULL, NULL, 0, TRUE, NULL, NULL, NULL, NULL);
INSERT INTO party VALUES ('navbharat nirman party', NULL, NULL, 0, TRUE, NULL, NULL, NULL, NULL);
INSERT INTO party VALUES ('nationalist congress party', NULL, NULL, 0, TRUE, NULL, NULL, NULL, NULL);
INSERT INTO party VALUES ('national congress of youth', NULL, NULL, 0, TRUE, NULL, NULL, NULL, NULL);
INSERT INTO party VALUES ('national development party', NULL, NULL, 0, TRUE, NULL, NULL, NULL, NULL);
INSERT INTO party VALUES ('national democratic peoples front', NULL, NULL, 0, TRUE, NULL, NULL, NULL, NULL);
INSERT INTO party VALUES ('nelopa(united)', NULL, NULL, 0, TRUE, NULL, NULL, NULL, NULL);
INSERT INTO party VALUES ('national lokhind party', NULL, NULL, 0, TRUE, NULL, NULL, NULL, NULL);
INSERT INTO party VALUES ('national loktantrik party', NULL, NULL, 0, TRUE, NULL, NULL, NULL, NULL);
INSERT INTO party VALUES ('namadhu makkal katchi', NULL, NULL, 0, TRUE, NULL, NULL, NULL, NULL);
INSERT INTO party VALUES ('nidaya malik (n) party', NULL, NULL, 0, TRUE, NULL, NULL, NULL, NULL);
INSERT INTO party VALUES ('national minorities party', NULL, NULL, 0, TRUE, NULL, NULL, NULL, NULL);
INSERT INTO party VALUES ('national organisation congress', NULL, NULL, 0, TRUE, NULL, NULL, NULL, NULL);
INSERT INTO party VALUES ('national panthers party', NULL, NULL, 0, TRUE, NULL, NULL, NULL, NULL);
INSERT INTO party VALUES ('nagaland peoples front', NULL, NULL, 0, TRUE, NULL, NULL, NULL, NULL);
INSERT INTO party VALUES ('national people''s party', NULL, NULL, 0, TRUE, NULL, NULL, NULL, NULL);
INSERT INTO party VALUES ('national republican party', NULL, NULL, 0, TRUE, NULL, NULL, NULL, NULL);
INSERT INTO party VALUES ('national secular party', NULL, NULL, 0, TRUE, NULL, NULL, NULL, NULL);
INSERT INTO party VALUES ('national students party', NULL, NULL, 0, TRUE, NULL, NULL, NULL, NULL);
INSERT INTO party VALUES ('niswarth sewa party', NULL, NULL, 0, TRUE, NULL, NULL, NULL, NULL);
INSERT INTO party VALUES ('naari shakti party', NULL, NULL, 0, TRUE, NULL, NULL, NULL, NULL);
INSERT INTO party VALUES ('ntr telugu desam party (lakshmi parvathi)', NULL, NULL, 0, TRUE, NULL, NULL, NULL, NULL);
INSERT INTO party VALUES ('national youth party', NULL, NULL, 0, TRUE, NULL, NULL, NULL, NULL);
INSERT INTO party VALUES ('orissa congress', NULL, NULL, 0, TRUE, NULL, NULL, NULL, NULL);
INSERT INTO party VALUES ('orissa mukti morcha', NULL, NULL, 0, TRUE, NULL, NULL, NULL, NULL);
INSERT INTO party VALUES ('praja bharath party', NULL, NULL, 0, TRUE, NULL, NULL, NULL, NULL);
INSERT INTO party VALUES ('phule bharti lok party', NULL, NULL, 0, TRUE, NULL, NULL, NULL, NULL);
INSERT INTO party VALUES ('paschim banga rajya muslim league', NULL, NULL, 0, TRUE, NULL, NULL, NULL, NULL);
INSERT INTO party VALUES ('people''s democratic alliance', NULL, NULL, 0, TRUE, NULL, NULL, NULL, NULL);
INSERT INTO party VALUES ('people''s democratic front', NULL, NULL, 0, TRUE, NULL, NULL, NULL, NULL);
INSERT INTO party VALUES ('people''s democratic forum', NULL, NULL, 0, TRUE, NULL, NULL, NULL, NULL);
INSERT INTO party VALUES ('people''s democratic movement', NULL, NULL, 0, TRUE, NULL, NULL, NULL, NULL);
INSERT INTO party VALUES ('peoples democratic party', NULL, NULL, 0, TRUE, NULL, NULL, NULL, NULL);
INSERT INTO party VALUES ('party for democratic socialism', NULL, NULL, 0, TRUE, NULL, NULL, NULL, NULL);
INSERT INTO party VALUES ('peace party', NULL, NULL, 0, TRUE, NULL, NULL, NULL, NULL);
INSERT INTO party VALUES ('peoples guardian', NULL, NULL, 0, TRUE, NULL, NULL, NULL, NULL);
INSERT INTO party VALUES ('pichhra samaj party', NULL, NULL, 0, TRUE, NULL, NULL, NULL, NULL);
INSERT INTO party VALUES ('pachai kudi makkal katchi', NULL, NULL, 0, TRUE, NULL, NULL, NULL, NULL);
INSERT INTO party VALUES ('punjab labour party', NULL, NULL, 0, TRUE, NULL, NULL, NULL, NULL);
INSERT INTO party VALUES ('pattali makkal katchi', NULL, NULL, 0, TRUE, NULL, NULL, NULL, NULL);
INSERT INTO party VALUES ('parmarth party', NULL, NULL, 0, TRUE, NULL, NULL, NULL, NULL);
INSERT INTO party VALUES ('pragatisheel manav samaj party', NULL, NULL, 0, TRUE, NULL, NULL, NULL, NULL);
INSERT INTO party VALUES ('puthiya needhi katchi', NULL, NULL, 0, TRUE, NULL, NULL, NULL, NULL);
INSERT INTO party VALUES ('praja party', NULL, NULL, 0, TRUE, NULL, NULL, NULL, NULL);
INSERT INTO party VALUES ('people''s party of arunachal', NULL, NULL, 0, TRUE, NULL, NULL, NULL, NULL);
INSERT INTO party VALUES ('peoples party of india(secular)', NULL, NULL, 0, TRUE, NULL, NULL, NULL, NULL);
INSERT INTO party VALUES ('pyramid party of india', NULL, NULL, 0, TRUE, NULL, NULL, NULL, NULL);
INSERT INTO party VALUES ('punjab pradesh vikash party', NULL, NULL, 0, TRUE, NULL, NULL, NULL, NULL);
INSERT INTO party VALUES ('praja rajyam party', NULL, NULL, 0, TRUE, NULL, NULL, NULL, NULL);
INSERT INTO party VALUES ('purvanchal rajya banao dal', NULL, NULL, 0, TRUE, NULL, NULL, NULL, NULL);
INSERT INTO party VALUES ('peoples republican party', NULL, NULL, 0, TRUE, NULL, NULL, NULL, NULL);
INSERT INTO party VALUES ('prabuddha republican party', NULL, NULL, 0, TRUE, NULL, NULL, NULL, NULL);
INSERT INTO party VALUES ('prism', NULL, NULL, 0, TRUE, NULL, NULL, NULL, NULL);
INSERT INTO party VALUES ('panchayat raj party', NULL, NULL, 0, TRUE, NULL, NULL, NULL, NULL);
INSERT INTO party VALUES ('professionals party of india', NULL, NULL, 0, TRUE, NULL, NULL, NULL, NULL);
INSERT INTO party VALUES ('prajatantrik samadhan party', NULL, NULL, 0, TRUE, NULL, NULL, NULL, NULL);
INSERT INTO party VALUES ('parivartan samaj party', NULL, NULL, 0, TRUE, NULL, NULL, NULL, NULL);
INSERT INTO party VALUES ('pragatisheel party', NULL, NULL, 0, TRUE, NULL, NULL, NULL, NULL);
INSERT INTO party VALUES ('proutist sarva samaj samiti', NULL, NULL, 0, TRUE, NULL, NULL, NULL, NULL);
INSERT INTO party VALUES ('puthiya tamilagam', NULL, NULL, 0, TRUE, NULL, NULL, NULL, NULL);
INSERT INTO party VALUES ('plains tribals council of assam', NULL, NULL, 0, TRUE, NULL, NULL, NULL, NULL);
INSERT INTO party VALUES ('proutist sarva samaj', NULL, NULL, 0, TRUE, NULL, NULL, NULL, NULL);
INSERT INTO party VALUES ('peasants and workers party of india', NULL, NULL, 0, TRUE, NULL, NULL, NULL, NULL);
INSERT INTO party VALUES ('rashtriya agraniye dal', NULL, NULL, 0, TRUE, NULL, NULL, NULL, NULL);
INSERT INTO party VALUES ('rashtriya janutthan party', NULL, NULL, 0, TRUE, NULL, NULL, NULL, NULL);
INSERT INTO party VALUES ('rashtriya lokwadi party', NULL, NULL, 0, TRUE, NULL, NULL, NULL, NULL);
INSERT INTO party VALUES ('rashtrawadi labour party', NULL, NULL, 0, TRUE, NULL, NULL, NULL, NULL);
INSERT INTO party VALUES ('rashtriya aikta manch', NULL, NULL, 0, TRUE, NULL, NULL, NULL, NULL);
INSERT INTO party VALUES ('rashtriya ali sena', NULL, NULL, 0, TRUE, NULL, NULL, NULL, NULL);
INSERT INTO party VALUES ('rashtriya sahara party', NULL, NULL, 0, TRUE, NULL, NULL, NULL, NULL);
INSERT INTO party VALUES ('rashtravadi aarthik swatantrata dal', NULL, NULL, 0, TRUE, NULL, NULL, NULL, NULL);
INSERT INTO party VALUES ('rashtriya janhit party', NULL, NULL, 0, TRUE, NULL, NULL, NULL, NULL);
INSERT INTO party VALUES ('rashtriya bahujan congress party', NULL, NULL, 0, TRUE, NULL, NULL, NULL, NULL);
INSERT INTO party VALUES ('rashtra bhakt dal', NULL, NULL, 0, TRUE, NULL, NULL, NULL, NULL);
INSERT INTO party VALUES ('rashtravadi communist party', NULL, NULL, 0, TRUE, NULL, NULL, NULL, NULL);
INSERT INTO party VALUES ('revolutionary communist party of india (rasik bhatt)', NULL, NULL, 0, TRUE, NULL, NULL, NULL, NULL);
INSERT INTO party VALUES ('rajyadhikara party', NULL, NULL, 0, TRUE, NULL, NULL, NULL, NULL);
INSERT INTO party VALUES ('rashtriya dehat morcha party', NULL, NULL, 0, TRUE, NULL, NULL, NULL, NULL);
INSERT INTO party VALUES ('rashtriya dharmanirpeksha nava bharat party', NULL, NULL, 0, TRUE, NULL, NULL, NULL, NULL);
INSERT INTO party VALUES ('rajasthan dev sena dal', NULL, NULL, 0, TRUE, NULL, NULL, NULL, NULL);
INSERT INTO party VALUES ('rashtriya garib dal', NULL, NULL, 0, TRUE, NULL, NULL, NULL, NULL);
INSERT INTO party VALUES ('rashtriya gondvana party', NULL, NULL, 0, TRUE, NULL, NULL, NULL, NULL);
INSERT INTO party VALUES ('rashtriya hamara dal', NULL, NULL, 0, TRUE, NULL, NULL, NULL, NULL);
INSERT INTO party VALUES ('rashtriya janadhikar party', NULL, NULL, 0, TRUE, NULL, NULL, NULL, NULL);
INSERT INTO party VALUES ('rashtriya janta congress', NULL, NULL, 0, TRUE, NULL, NULL, NULL, NULL);
INSERT INTO party VALUES ('rashtriya janata dal', NULL, NULL, 0, TRUE, NULL, NULL, NULL, NULL);
INSERT INTO party VALUES ('rashtriya janandholan paksha', NULL, NULL, 0, TRUE, NULL, NULL, NULL, NULL);
INSERT INTO party VALUES ('rashtriya jan-jagram morcha', NULL, NULL, 0, TRUE, NULL, NULL, NULL, NULL);
INSERT INTO party VALUES ('rashtriya janwadi party (krantikari)', NULL, NULL, 0, TRUE, NULL, NULL, NULL, NULL);
INSERT INTO party VALUES ('rashtriya jan sahay dal', NULL, NULL, 0, TRUE, NULL, NULL, NULL, NULL);
INSERT INTO party VALUES ('rajasthan vikas party', NULL, NULL, 0, TRUE, NULL, NULL, NULL, NULL);
INSERT INTO party VALUES ('rashtriya krantikari janata party', NULL, NULL, 0, TRUE, NULL, NULL, NULL, NULL);
INSERT INTO party VALUES ('rashtriya krantikari samajwadi party', NULL, NULL, 0, TRUE, NULL, NULL, NULL, NULL);
INSERT INTO party VALUES ('rashtriya lok dal', NULL, NULL, 0, TRUE, NULL, NULL, NULL, NULL);
INSERT INTO party VALUES ('rashtriya lokhit party', NULL, NULL, 0, TRUE, NULL, NULL, NULL, NULL);
INSERT INTO party VALUES ('rashtriya lok seva morcha', NULL, NULL, 0, TRUE, NULL, NULL, NULL, NULL);
INSERT INTO party VALUES ('rashtriya mazdoor ekta party', NULL, NULL, 0, TRUE, NULL, NULL, NULL, NULL);
INSERT INTO party VALUES ('rashtriya mangalam party', NULL, NULL, 0, TRUE, NULL, NULL, NULL, NULL);
INSERT INTO party VALUES ('rashtriya muslim mujhahid party', NULL, NULL, 0, TRUE, NULL, NULL, NULL, NULL);
INSERT INTO party VALUES ('rashtriya machhua samaj party', NULL, NULL, 0, TRUE, NULL, NULL, NULL, NULL);
INSERT INTO party VALUES ('rashtriya naujawan dal', NULL, NULL, 0, TRUE, NULL, NULL, NULL, NULL);
INSERT INTO party VALUES ('rajya nojawan shakti party', NULL, NULL, 0, TRUE, NULL, NULL, NULL, NULL);
INSERT INTO party VALUES ('republican paksha (khoripa)', NULL, NULL, 0, TRUE, NULL, NULL, NULL, NULL);
INSERT INTO party VALUES ('rashtriya praja congress (secular)', NULL, NULL, 0, TRUE, NULL, NULL, NULL, NULL);
INSERT INTO party VALUES ('rashtriya parivartan dal', NULL, NULL, 0, TRUE, NULL, NULL, NULL, NULL);
INSERT INTO party VALUES ('republican party of india', NULL, NULL, 0, TRUE, NULL, NULL, NULL, NULL);
INSERT INTO party VALUES ('republican party of india (a)', NULL, NULL, 0, TRUE, NULL, NULL, NULL, NULL);
INSERT INTO party VALUES ('republican party of india (democratic )', NULL, NULL, 0, TRUE, NULL, NULL, NULL, NULL);
INSERT INTO party VALUES ('republican party of india (khobragade)', NULL, NULL, 0, TRUE, NULL, NULL, NULL, NULL);
INSERT INTO party VALUES ('republician party of india ektawadi', NULL, NULL, 0, TRUE, NULL, NULL, NULL, NULL);
INSERT INTO party VALUES ('rashtriya pragati party', NULL, NULL, 0, TRUE, NULL, NULL, NULL, NULL);
INSERT INTO party VALUES ('republican presidium party of india', NULL, NULL, 0, TRUE, NULL, NULL, NULL, NULL);
INSERT INTO party VALUES ('rashtriya rajdhani congress delhi', NULL, NULL, 0, TRUE, NULL, NULL, NULL, NULL);
INSERT INTO party VALUES ('rashtriya raksha dal', NULL, NULL, 0, TRUE, NULL, NULL, NULL, NULL);
INSERT INTO party VALUES ('rayalaseema rashtra samithi', NULL, NULL, 0, TRUE, NULL, NULL, NULL, NULL);
INSERT INTO party VALUES ('rashtriya swabhimaan party', NULL, NULL, 0, TRUE, NULL, NULL, NULL, NULL);
INSERT INTO party VALUES ('rashtriya sawarn dal', NULL, NULL, 0, TRUE, NULL, NULL, NULL, NULL);
INSERT INTO party VALUES ('rashtriya garima party', NULL, NULL, 0, TRUE, NULL, NULL, NULL, NULL);
INSERT INTO party VALUES ('rashtriya sakar party', NULL, NULL, 0, TRUE, NULL, NULL, NULL, NULL);
INSERT INTO party VALUES ('rashtriya samanta dal', NULL, NULL, 0, TRUE, NULL, NULL, NULL, NULL);
INSERT INTO party VALUES ('rashtriya samajik nayak paksha', NULL, NULL, 0, TRUE, NULL, NULL, NULL, NULL);
INSERT INTO party VALUES ('revolutionary socialist party', NULL, NULL, 0, TRUE, NULL, NULL, NULL, NULL);
INSERT INTO party VALUES ('rastriya samajwadi party (secular)', NULL, NULL, 0, TRUE, NULL, NULL, NULL, NULL);
INSERT INTO party VALUES ('rashtriya samaj paksha', NULL, NULL, 0, TRUE, NULL, NULL, NULL, NULL);
INSERT INTO party VALUES ('rashtriya surya prakash party', NULL, NULL, 0, TRUE, NULL, NULL, NULL, NULL);
INSERT INTO party VALUES ('rashtra sewa dal', NULL, NULL, 0, TRUE, NULL, NULL, NULL, NULL);
INSERT INTO party VALUES ('rashtriya kranti party', NULL, NULL, 0, TRUE, NULL, NULL, NULL, NULL);
INSERT INTO party VALUES ('rashtriya unnatisheel dal', NULL, NULL, 0, TRUE, NULL, NULL, NULL, NULL);
INSERT INTO party VALUES ('rashtravadi janata party', NULL, NULL, 0, TRUE, NULL, NULL, NULL, NULL);
INSERT INTO party VALUES ('rashtriya vikas party', NULL, NULL, 0, TRUE, NULL, NULL, NULL, NULL);
INSERT INTO party VALUES ('rashtrawadi sena', NULL, NULL, 0, TRUE, NULL, NULL, NULL, NULL);
INSERT INTO party VALUES ('rashtrawadi samaj party', NULL, NULL, 0, TRUE, NULL, NULL, NULL, NULL);
INSERT INTO party VALUES ('rashtriya yuva sangh', NULL, NULL, 0, TRUE, NULL, NULL, NULL, NULL);
INSERT INTO party VALUES ('shiromani akali dal', NULL, NULL, 0, TRUE, NULL, NULL, NULL, NULL);
INSERT INTO party VALUES ('shiromani akali dal (amritsar)(simranjit singh mann)', NULL, NULL, 0, TRUE, NULL, NULL, NULL, NULL);
INSERT INTO party VALUES ('samruddha odisha', NULL, NULL, 0, TRUE, NULL, NULL, NULL, NULL);
INSERT INTO party VALUES ('samata party', NULL, NULL, 0, TRUE, NULL, NULL, NULL, NULL);
INSERT INTO party VALUES ('sadbhavana party', NULL, NULL, 0, TRUE, NULL, NULL, NULL, NULL);
INSERT INTO party VALUES ('shikshit berozgar sena', NULL, NULL, 0, TRUE, NULL, NULL, NULL, NULL);
INSERT INTO party VALUES ('suheldev bhartiya samaj party', NULL, NULL, 0, TRUE, NULL, NULL, NULL, NULL);
INSERT INTO party VALUES ('sikkim democratic front', NULL, NULL, 0, TRUE, NULL, NULL, NULL, NULL);
INSERT INTO party VALUES ('socialistic democratic party', NULL, NULL, 0, TRUE, NULL, NULL, NULL, NULL);
INSERT INTO party VALUES ('sarvadharam party (madhya pradesh)', NULL, NULL, 0, TRUE, NULL, NULL, NULL, NULL);
INSERT INTO party VALUES ('save goa front', NULL, NULL, 0, TRUE, NULL, NULL, NULL, NULL);
INSERT INTO party VALUES ('sikkim gorkha prajatantric party', NULL, NULL, 0, TRUE, NULL, NULL, NULL, NULL);
INSERT INTO party VALUES ('sikkim himali rajya parishad party', NULL, NULL, 0, TRUE, NULL, NULL, NULL, NULL);
INSERT INTO party VALUES ('shivsena', NULL, NULL, 0, TRUE, NULL, NULL, NULL, NULL);
INSERT INTO party VALUES ('sarb hind shiromani akali dal', NULL, NULL, 0, TRUE, NULL, NULL, NULL, NULL);
INSERT INTO party VALUES ('shoshit samaj party', NULL, NULL, 0, TRUE, NULL, NULL, NULL, NULL);
INSERT INTO party VALUES ('sikkim jan-ekta party', NULL, NULL, 0, TRUE, NULL, NULL, NULL, NULL);
INSERT INTO party VALUES ('samajwadi janata party (rashtriya)', NULL, NULL, 0, TRUE, NULL, NULL, NULL, NULL);
INSERT INTO party VALUES ('samajik jantantrik party', NULL, NULL, 0, TRUE, NULL, NULL, NULL, NULL);
INSERT INTO party VALUES ('sarvodaya karnataka paksha', NULL, NULL, 0, TRUE, NULL, NULL, NULL, NULL);
INSERT INTO party VALUES ('social action party', NULL, NULL, 0, TRUE, NULL, NULL, NULL, NULL);
INSERT INTO party VALUES ('socialist party (lohia)', NULL, NULL, 0, TRUE, NULL, NULL, NULL, NULL);
INSERT INTO party VALUES ('smast bhartiya party', NULL, NULL, 0, TRUE, NULL, NULL, NULL, NULL);
INSERT INTO party VALUES ('samata samaj party', NULL, NULL, 0, TRUE, NULL, NULL, NULL, NULL);
INSERT INTO party VALUES ('samajwadi party', NULL, NULL, 0, TRUE, NULL, NULL, NULL, NULL);
INSERT INTO party VALUES ('secular party of india', NULL, NULL, 0, TRUE, NULL, NULL, NULL, NULL);
INSERT INTO party VALUES ('sirpanch samaj party', NULL, NULL, 0, TRUE, NULL, NULL, NULL, NULL);
INSERT INTO party VALUES ('sampurna vikas dal', NULL, NULL, 0, TRUE, NULL, NULL, NULL, NULL);
INSERT INTO party VALUES ('socialist republican party', NULL, NULL, 0, TRUE, NULL, NULL, NULL, NULL);
INSERT INTO party VALUES ('shakti sena (bharat desh)', NULL, NULL, 0, TRUE, NULL, NULL, NULL, NULL);
INSERT INTO party VALUES ('shoshit samaj dal', NULL, NULL, 0, TRUE, NULL, NULL, NULL, NULL);
INSERT INTO party VALUES ('sanatan samaj party', NULL, NULL, 0, TRUE, NULL, NULL, NULL, NULL);
INSERT INTO party VALUES ('sikkim sangram parishad', NULL, NULL, 0, TRUE, NULL, NULL, NULL, NULL);
INSERT INTO party VALUES ('swatantra bharat paksha', NULL, NULL, 0, TRUE, NULL, NULL, NULL, NULL);
INSERT INTO party VALUES ('samajtantric party of india', NULL, NULL, 0, TRUE, NULL, NULL, NULL, NULL);
INSERT INTO party VALUES ('sunder samaj party', NULL, NULL, 0, TRUE, NULL, NULL, NULL, NULL);
INSERT INTO party VALUES ('sardar vallabhbhai patel party', NULL, NULL, 0, TRUE, NULL, NULL, NULL, NULL);
INSERT INTO party VALUES ('shivrajya party', NULL, NULL, 0, TRUE, NULL, NULL, NULL, NULL);
INSERT INTO party VALUES ('savarn samaj party', NULL, NULL, 0, TRUE, NULL, NULL, NULL, NULL);
INSERT INTO party VALUES ('swaraj dal', NULL, NULL, 0, TRUE, NULL, NULL, NULL, NULL);
INSERT INTO party VALUES ('samajwadi jan parishad', NULL, NULL, 0, TRUE, NULL, NULL, NULL, NULL);
INSERT INTO party VALUES ('swabhimani paksha', NULL, NULL, 0, TRUE, NULL, NULL, NULL, NULL);
INSERT INTO party VALUES ('swarajya party of india', NULL, NULL, 0, TRUE, NULL, NULL, NULL, NULL);
INSERT INTO party VALUES ('tamil desiyak katchi', NULL, NULL, 0, TRUE, NULL, NULL, NULL, NULL);
INSERT INTO party VALUES ('telugu desam', NULL, NULL, 0, TRUE, NULL, NULL, NULL, NULL);
INSERT INTO party VALUES ('telangana praja party', NULL, NULL, 0, TRUE, NULL, NULL, NULL, NULL);
INSERT INTO party VALUES ('tharasu makkal mandram', NULL, NULL, 0, TRUE, NULL, NULL, NULL, NULL);
INSERT INTO party VALUES ('the humanist party of india', NULL, NULL, 0, TRUE, NULL, NULL, NULL, NULL);
INSERT INTO party VALUES ('tamilaga janata', NULL, NULL, 0, TRUE, NULL, NULL, NULL, NULL);
INSERT INTO party VALUES ('tamil maanila congress (moopanar)', NULL, NULL, 0, TRUE, NULL, NULL, NULL, NULL);
INSERT INTO party VALUES ('trinamool gana parishad', NULL, NULL, 0, TRUE, NULL, NULL, NULL, NULL);
INSERT INTO party VALUES ('tamil nadu peasants & workers party', NULL, NULL, 0, TRUE, NULL, NULL, NULL, NULL);
INSERT INTO party VALUES ('trilinga praja pragati party', NULL, NULL, 0, TRUE, NULL, NULL, NULL, NULL);
INSERT INTO party VALUES ('tamizhaga rajiv congress', NULL, NULL, 0, TRUE, NULL, NULL, NULL, NULL);
INSERT INTO party VALUES ('the religion of man revolving political party of indi', NULL, NULL, 0, TRUE, NULL, NULL, NULL, NULL);
INSERT INTO party VALUES ('telangana rashtra samithi', NULL, NULL, 0, TRUE, NULL, NULL, NULL, NULL);
INSERT INTO party VALUES ('united bodo nationalist liberation front', NULL, NULL, 0, TRUE, NULL, NULL, NULL, NULL);
INSERT INTO party VALUES ('united citizens party', NULL, NULL, 0, TRUE, NULL, NULL, NULL, NULL);
INSERT INTO party VALUES ('united communist party of india', NULL, NULL, 0, TRUE, NULL, NULL, NULL, NULL);
INSERT INTO party VALUES ('united democratic party', NULL, NULL, 0, TRUE, NULL, NULL, NULL, NULL);
INSERT INTO party VALUES ('united goans democratic party', NULL, NULL, 0, TRUE, NULL, NULL, NULL, NULL);
INSERT INTO party VALUES ('uttarakhand kranti dal', NULL, NULL, 0, TRUE, NULL, NULL, NULL, NULL);
INSERT INTO party VALUES ('united minorities front', NULL, NULL, 0, TRUE, NULL, NULL, NULL, NULL);
INSERT INTO party VALUES ('ulzaipali makkal katchy', NULL, NULL, 0, TRUE, NULL, NULL, NULL, NULL);
INSERT INTO party VALUES ('united national loktantrik party', NULL, NULL, 0, TRUE, NULL, NULL, NULL, NULL);
INSERT INTO party VALUES ('uttar pradesh republican party', NULL, NULL, 0, TRUE, NULL, NULL, NULL, NULL);
INSERT INTO party VALUES ('united reservation movement council of assam', NULL, NULL, 0, TRUE, NULL, NULL, NULL, NULL);
INSERT INTO party VALUES ('urs samyuktha paksha', NULL, NULL, 0, TRUE, NULL, NULL, NULL, NULL);
INSERT INTO party VALUES ('united tribal nationalists liberation front', NULL, NULL, 0, TRUE, NULL, NULL, NULL, NULL);
INSERT INTO party VALUES ('united women front', NULL, NULL, 0, TRUE, NULL, NULL, NULL, NULL);
INSERT INTO party VALUES ('vanchit jamat party', NULL, NULL, 0, TRUE, NULL, NULL, NULL, NULL);
INSERT INTO party VALUES ('viduthalai chiruthaigal katchi', NULL, NULL, 0, TRUE, NULL, NULL, NULL, NULL);
INSERT INTO party VALUES ('vishva hindustani sangathan', NULL, NULL, 0, TRUE, NULL, NULL, NULL, NULL);
INSERT INTO party VALUES ('vidharbha janata congress', NULL, NULL, 0, TRUE, NULL, NULL, NULL, NULL);
INSERT INTO party VALUES ('vijeta party', NULL, NULL, 0, TRUE, NULL, NULL, NULL, NULL);
INSERT INTO party VALUES ('vikas party', NULL, NULL, 0, TRUE, NULL, NULL, NULL, NULL);
INSERT INTO party VALUES ('vidharbha rajya party', NULL, NULL, 0, TRUE, NULL, NULL, NULL, NULL);
INSERT INTO party VALUES ('vishwa vikas sangh', NULL, NULL, 0, TRUE, NULL, NULL, NULL, NULL);
INSERT INTO party VALUES ('west bengal trinamool congress', NULL, NULL, 0, TRUE, NULL, NULL, NULL, NULL);
INSERT INTO party VALUES ('youth for equality', NULL, NULL, 0, TRUE, NULL, NULL, NULL, NULL);
INSERT INTO party VALUES ('yuva gantantra party', NULL, NULL, 0, TRUE, NULL, NULL, NULL, NULL);
INSERT INTO party VALUES ('youth and students party', NULL, NULL, 0, TRUE, NULL, NULL, NULL, NULL);
INSERT INTO party VALUES ('yuva vikas party', NULL, NULL, 0, TRUE, NULL, NULL, NULL, NULL);
INSERT INTO party VALUES ('independent', NULL, NULL, 0, TRUE, NULL, NULL, NULL, NULL);